### ISSUE TITLE
Correct Root: and Kernel:Args: settings for SELinux [Documentation?]

### ISSUE THREAD

**Issue by NateCrawford** [warewulf/warewulf#1001]
### Steps to reproduce

  The documentation for enabling SELinux (https://warewulf.org/docs/development/contents/security.html#selinux) says that the provisioning file system needs to be of type tmpfs, but only setting this (--root tmpfs) hits an error message requiring "rootfstype=ramfs" to be added to the kernel args: https://github.com/hpcng/warewulf/blob/2196417b79f10e15ccd0fb86f04f675997a2fc1f/overlays/wwinit/init#L38 

  I was trying to diagnose this from a remote connection, so couldn't see the error output from init. Even when I got on-site, the error message requesting "ramfs" seemed to conflict with the --root setting of "tmpfs", but it does seem to work OK.

  Can the extra kernel arg recommendation be added to the documentation? It would have saved me a bit of time and headache.

### Information on your system

wwctl version:   4.4.0-1.git_afcdb21
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0-1.git_afcdb21"

NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
Thanks for this report, and sorry for not seeing it until now, @NateCrawford. I have encountered this as well, and definitely want to get this resolved.
