### ISSUE TITLE
Remove net.naming-scheme=v238 from default kernel args

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#1012]
It took me a while to realize why Warewulf nodes don't use consistent interface naming by default. I think it's because we're specifying `net.naming-scheme=v238` as a default kernel arg.

I suggest that this should be made non-default behavior and moved to documentation.

This should make it easier to fix #962, though I'm not 100% certain of that yet.

https://www.freedesktop.org/software/systemd/man/latest/systemd.net-naming-scheme.html

**Comment by mslacken** [comment]
The naming scheme was brought in, to have a stable naming for the infiniband interfaces in combination with NetworkManager. If we have another solution, we can drop it.
