### ISSUE TITLE
Update CHANGELOG and warewulf.spec %changelog

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#1013]
We haven't been maintaining the changelog in warewulf.spec; so I want to get it updated for 4.5.0.

That changelog, as I understand it, doesn't need to reflect all changes in the software; only changes in the packaging. But I'll look into it further.

I also want to audit the CHANGELOG in prep for v4.5.0.

**Comment by mslacken** [comment]
For suse like distros the changeling is in a separate file. For its contents I would use whatever we put on the GitHub release page. So you could do the same for the spec file
