### ISSUE TITLE
ipaddr in configuration expecting CIDR notation

### ISSUE THREAD

**Issue by brianphan** [warewulf/warewulf#1016]
### Steps to reproduce

Configuration File (/etc/warewwulf/warewulf.conf)
```
dhcp:
    enabled: true
    range end: 10.0.1.255
    range start: 10.0.1.1
    systemd name: dhcpd
    template: default
ipaddr: 10.0.0.3
netmask: 255.255.252.0
nfs:
    enabled: true
    export paths:
    -   export options: rw,sync
        mount: true
        mount options: defaults
        path: /home
    -   export options: rw,sync,no_root_squash
        mount: true
        mount options: defaults
        path: /opt/ohpc/pub
    systemd name: nfs-server
tftp:
    enabled: true
    systemd name: tftp
    tftproot: /var/lib/tftpboot
warewulf:
    autobuild overlays: true
    datastore: ''
    host overlay: true
    port: 9873
    secure: false
    syslog: false
    update interval: 60
```
Call `wwctl configure --all`

### Error message

```
$ wwctl configure --all
ERROR: Couldn't parse IP address: invalid CIDR address: 10.0.0.3
```
However, if you update `ipaddr` in the configuration to `10.0.0.3/22`, the error is mitigated, but configuration of dhcpd breaks since we're rendering `http://10.0.0.3/22:9873` in `/etc/dhcpd.conf`. 

### Information on your system

This is a bug currently on the main branch
```
$ wwctl version
wwctl version:	 4.5.x-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.x-1"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
It looks to me like this happens if you don't specify `network`. At that point, it expects to be able to get all the info from a CIDR `ipaddr`. It looks like this generally works, except ipaddr needs to be updated internally to only have the ip address part, not the full CIDR address. (Since that's what the downstream templates expect.)
