### ISSUE TITLE
Make current overlay name visible to templates

### ISSUE THREAD

**Issue by griznog** [warewulf/warewulf#1052]
### Summary

Make the current overlay being rendered's name visible to templates, e.g. `{{ .Overlay }}` would resolve to `wwinit` when rendering things in the `wwinit` overlay.

### Rationale

It would be nice to have the current overlay name available in templates. For instance, if an overlay sets up a systemd service, then it might use the overlay name to build the ExecStart line:
```
[Service]
ExecStart=/warewulf/sbin/service.{{ .Overlay }}.sh
```
This is a step towards having a basic systemd service template that can be easily reused without needing to go and edit each file to update things that include the overlay name. 

### Description

`{{ .Overlay }}`  should resolve in templates to the current overlay name being rendered.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mslacken** [comment]
Was a  bit more tricky than though initially, but should work now,
