### ISSUE TITLE
disk management wipe partition doesn't seem to work 

### ISSUE THREAD

**Issue by henkela** [warewulf/warewulf#1063]
### Steps to reproduce

```console
wwctl node set <node> --diskname /dev/sda --diskwipe --partname scratch --partcreate --fsname scratch --fsformat ext4 --fspath /localscratch --fswipe
wwctl power reset <node>
```
After boot and verification that partition scratch is created (and mounted on /localscratch) 
```console 
wwctl ssh <node> "blkid && lsblk && df"
```
Then undefine disk,partition, and fs
```console
wwctl node set <node>--partdel scratch --fsdel /dev/disk/by-partlabel/scratch --diskdel /dev/sda 
```
(by the way, it's counterintuitive that the full systempath is needed for --fsdel instead of just the partlabel) 
Finally, readded the disk with a different fsformat (to make sure to see whether ignition tries to create or reuse) 
```console
wwctl node set <node> --diskname /dev/sda --diskwipe --partname scratch --partcreate --fsname scratch --fsformat xfs --fspath /localscratch --fswipe
wwctl power reset <node>
```
### Expected result:
since --fswipe and --diskwipe is set I expected that the partition table would be wiped and the partition would be recreated with format xfs. 
### Actual result:
Instead 
```console 
wwctl ssh <node> "file -sL /dev/sda1"
<node>: /dev/sda1: Linux rev 1.0 ext4 filesystem data, UUID=6f2c90e5-1d72-4a89-a784-a889d031ad15 (needs journal recovery) (extents) (64bit) (large files) (huge files)
```
the partition is still ext4, hence neither partition table nor fs seem to be wiped. 
The ignition-file looks ok: 
```console
{"ignition":{"version":"3.1.0"},"storage":{"disks":[{"device":"/dev/sda","partitions":[{"label":"scratch","shouldExist":true,"wipePartitionEntry":false}],"wipeTable":true}],"filesystems":[{"device":"/dev/disk/by-partlabel/scratch","format":"xfs","path":"/localscratch","wipeFilesystem":true}]}}
```
except that the wipePartitionEntry is false whereas I would have expected a true. Furthermore, it seems like there is no way to set wipePartitionEntry to true in warewulf. 

### Error message

systemctl status localscratch.mount 
```console 
mount: /localscratch: wrong fs type, bad option, bad superblock on /dev/sda1, missing codepage or helper program, or other error.
```
which is obviously because after the change it tries to mount -t xfs but the partition stayed ext4. 

### Information on your system

wwctl version:	 4.5.x-1
NAME="AlmaLinux"
VERSION="9.2 (Turquoise Kodkod)"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by henkela** [comment]
Never mind... this was an overlapping admin action problem. The second admin changed the container which did not contain ignition hence no partitions were created.

**Comment by mslacken** [comment]
Yes, you are right the `WipePartitionEntry` is not accessible with `wwctl node set`, but via `wwctl node edit` or by setting it directly in `node.conf` where its name is `wipe_partition_entry` in the `partitions` section.
Some of the options for `ignition` are missing form the `wwctl` commands, in order not to overload the help output.

**Comment by henkela** [comment]
Thanks for clearing that up!

**Comment by henkela** [comment]
I'll try to add it to the docs - that is to say, the fact that the wwctl node set options are only for simple cases and that manual editing of nodes.conf may be necessary to achieve the expected partition layout.
