### ISSUE TITLE
Enhancements for behavior of `wwctl configure`

### ISSUE THREAD

**Issue by MiddelkoopT** [warewulf/warewulf#1075]
### Summary

When using `wwwctl configure` it does not behave as one would expect and could have some better error messages, especially for new users

### Rationale

When running `wwctl configure --all` and things like dhcp are turned off the command will stop configuration at that point and not indicate that others (such as ssh) did not run.

When running `wwctl configure dhcp tftp` (multiple configurations) it does not configure the ones listed and fails silently.

Error messages are not very clear/verbose, since most of the time the error could prevent ww4 from working.

### Description

When using `wwctl configure --all` all failed configurations should be indicated (not just the first one), and indicated with an ERROR (the current messages are not that explicit)

When using `wwctl configure dhcp tftp...` either any listed service be configured, or an error message indicating only one 

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by anderbubble** [comment]
Thanks for the report, @MiddelkoopT!

**Comment by anderbubble** [comment]
I think this is fixed in #1360 now, included in the v4.5.7 release.
