### ISSUE TITLE
How to remove default ssh host keys from wwinit overlay?

### ISSUE THREAD

**Issue by posch** [warewulf/warewulf#1080]
### Steps to reproduce

1. Install warewulf from RPM package.
2. Delete /var/lib/warewulf/overlays/wwinit/etc/ssh, because ssh host keys are part of the image.
3. Update warewulf using an RPM package.

After the package update/reinstall, /var/lib/warewulf/overlays/wwinit/etc/ssh/ssh_host_rsa_key.ww et al have been reinstalled. By default, they contain "include" directives like this:

    {{Include "keys/ssh_host_rsa_key"}}

Since keys are part of the image, there is no /etc/warewulf/keys. Thus, empty files are generated. This triggers sshd-keygen on Rocky 8, which has sshd-keygen@xxx.service units that will generate fresh keys, if:

    ConditionFileNotEmpty=|!/etc/ssh/ssh_host_%i_key

So, after updating warewulf from RPM, my test node had wrong ssh keys, because I forgot that I have deleted these files from the wwini overlay.

I wonder if there's a way to remove the ssh host keys from wwinit that survives a package update.

### Information on your system

warewulf version d6f6fedb1510ee1a8a4fa937a71ad3ff2190a5bb (v4.4.x branch) on Rocky 8.9.

Rocky 8.9 images.

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@posch thanks for the report! We'll evaluate and try to get this situation more clearly documented.

**Comment by griznog** [comment]
I don't think this can be fixed in current WW, guessing it wasn't anticipated that keys would be placed into the image rather than being pulled in from the master WW config. This self resolves if/when we make progress on #987 which will likely see ssh keys moved into a distinct overlay and thus it'd just be a matter of excluding that overlay from the list of overlays a node receives.

**Comment by anderbubble** [comment]
@posch on further consideration, I think that #987 will resolve this for you, as it splits the population of ssh host keys into its own overlay which may be omitted from your nodes/profiles.
