### ISSUE TITLE
Collate wwctl ssh-output / parallel ssh

### ISSUE THREAD

**Issue by henkela** [warewulf/warewulf#1081]
### Summary

```
It would be great to have a feature similar to the xcat-commands
xdsh gpu00[02-10] "<cmd>"|xdshbak -c
HOSTS -------------------------------------------------------------------------
gpu0002, gpu0003, gpu0004, gpu0005, gpu0006, gpu0007, gpu0008, gpu0009, gpu0010
-------------------------------------------------------------------------------
<same output>
```

Maybe an option on wwctl ssh is possible to aggregate nodes with the same output. 

### Description

Of course, it is possible to grep and uniq output. Yet for a more comfortable overview it would be nice to have a builtin tool.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mslacken** [comment]
@henkela Can you please elaborate why `wwctl ssh $NODERANGE $CMD` is not sufficient?
I don't know how the xcat commands work, so what is the difference here?

**Comment by henkela** [comment]
I think this can be closed. I just found that clustershell supports what I'd like to have: 
clush | clubak 
https://clustershell.readthedocs.io/en/latest/tools/clubak.html
So no need to rewrite an existing tool except you have too much free time ;)
Only downside: wwctl is not avail as external source yet

**Comment by mslacken** [comment]
You cab get a genders database from the template under `etc/examples/genders.ww` and use this as an input for variois tools.
