### ISSUE TITLE
Error setting profile on node

### ISSUE THREAD

**Issue by robilic** [warewulf/warewulf#1085]
From documentation:

https://warewulf.org/docs/development/contents/profiles.html#multiple-profiles

    $ wwctl node set --addprofile myProfile compute001
    ERROR: unknown flag: --addprofile

Shouldn't this be:

    $ wwctl node set -P myProfile compute001

    $ wwctl version
    wwctl version:   4.4.0-1.git_afcdb21
    rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.4.0-1.git_afcdb21"

**Comment by anderbubble** [comment]
Thanks for the call-out. We've got a lot of documentation work to do, and we'll make sure this is updated.
