### ISSUE TITLE
Resolve security-related dependabot issues

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#1096]
Dependabot is reporting issues with Warewulf. It as already generated a few PRs, but it will do more as we complete those which are already submitted.

https://github.com/warewulf/warewulf/security/dependabot

**Comment by anderbubble** [comment]
- https://github.com/warewulf/warewulf/pull/1084
- https://github.com/warewulf/warewulf/pull/1082
- https://github.com/warewulf/warewulf/pull/1044
- https://github.com/warewulf/warewulf/pull/1029
- https://github.com/warewulf/warewulf/pull/872

**Comment by JasonYangShadow** [comment]
Prior PR
https://github.com/warewulf/warewulf/pull/1104

**Comment by JasonYangShadow** [comment]
@anderbubble @mslacken 

Updates:
1. PR https://github.com/warewulf/warewulf/pull/1104 gets successfully merged
2. After the above PR gets merged, I did double verification on the dependabot created PRs
    https://github.com/warewulf/warewulf/pulls/app%2Fdependabot
    4 of 5 are confirmed as not breaking the build and further tests.  (These good PRs are marked with an `okay` label)
    1 of 5 is confirmed broken currently, and the related error requires a higher version of golang, i.e. 1.20.0 (This PR is marked with a `broken` label)

```
Run make vet
fatal: No names found, cannot describe anything.
go vet ./...
# github.com/sigstore/sigstore/pkg/signature
Error: vendor/github.com/sigstore/sigstore/pkg/signature/ed2[5](https://github.com/warewulf/warewulf/actions/runs/8293510677/job/22697492802?pr=1122#step:4:6)519ph.go:150:20: undefined: ed25519.VerifyWithOptions
Error: vendor/github.com/sigstore/sigstore/pkg/signature/ed25519ph.go:150:[7](https://github.com/warewulf/warewulf/actions/runs/8293510677/job/22697492802?pr=1122#step:4:8)8: undefined: ed25519.Options
note: module requires Go 1.20
make: *** [Makefile:75: vet] Error 1
Error: Process completed with exit code 2.
```
Personally, I think we might need to skip this broken PR (close it). Upgrading the golang version to 1.20.0 for this broken PR might be not that worthwhile.

**Comment by anderbubble** [comment]
@JasonYangShadow thank you for reviewing the dependabot issues. I see that you labeled them "okay"; but can you approve them with a review in stead? That way I can merge them without violating our GitHub policy.

Thanks!

**Comment by anderbubble** [comment]
> Upgrading the golang version to 1.20.0 for this one library update might be not that worthwhile.

@JasonYangShadow is there a reason we _shouldn't_ upgrade golang to 1.20? Does doing so break other things?

**Comment by JasonYangShadow** [comment]
> > Upgrading the golang version to 1.20.0 for this one library update might be not that worthwhile.
> 
> @JasonYangShadow is there a reason we _shouldn't_ upgrade golang to 1.20? Does doing so break other things?

no specifically, I manually tested go 1.20 for the broken library in the github action.
![image](https://github.com/warewulf/warewulf/assets/2051711/a981292d-d9ac-4e3b-ab89-ded68740f3c7)

it looks like 1.20 should work fine with the broken PR. But this will need another agreement from the community (whether we are okay to upgrade to go 1.20). 😄

**Comment by JasonYangShadow** [comment]
@anderbubble @mslacken 
As we have successfully upgrade the minimum golang version to 1.20
All dependabot created PRs work fine on this version
https://github.com/warewulf/warewulf/pulls/app%2Fdependabot
I have approved all PRs, please feel free to merge.

**Comment by anderbubble** [comment]
@JasonYangShadow I merged all the dependabot issues that you had reviewed. Dependabot limits the number of active PRs it submits at any one time; so there are more that were masked. You can see the issues they address here:

https://github.com/warewulf/warewulf/security/dependabot

But I think we've just got four more:

- https://github.com/warewulf/warewulf/pull/1160
- https://github.com/warewulf/warewulf/pull/1159
- https://github.com/warewulf/warewulf/pull/1158
- https://github.com/warewulf/warewulf/pull/1157

Could you review those, too?

**Comment by JasonYangShadow** [comment]
@anderbubble 

Please note that https://github.com/warewulf/warewulf/pull/1157 this PR requires additional manual code changes. 
Others look good!
