### ISSUE TITLE
update linter

### ISSUE THREAD

**Issue by mslacken** [warewulf/warewulf#1099]
### Steps to reproduce

```make lint```

### Error message

```golangci/golangci-lint info installed .tools/bin/golangci-lint
.tools/bin/golangci-lint run --build-tags "containers_image_openpgp containers_image_ostree" --timeout=5m ./...
../../../../../../usr/share/go/1.21/src/net/http/internal/chunked.go:79:14: undefined: max (typecheck)
	cr.excess = max(cr.excess, 0)
	            ^
make: *** [Makefile:71: lint] Error 1
```

### Information on your system

ERROR  : version: 4.5.0rc1 relase: 1.git_88446f95 WW_INTERNAL: 45
AME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
I am able to run lint on a current LEAP release; so I'm assuming this has been resolved.

```
8f34d0e57c41:/warewulf # make lint
.tools/bin/golangci-lint run --build-tags "containers_image_openpgp containers_image_ostree" --timeout=5m ./...
8f34d0e57c41:/warewulf # cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.6"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.6"
PRETTY_NAME="openSUSE Leap 15.6"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.6"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```
