### ISSUE TITLE
warewulf rendered dnsmasq constantly boots ipxe image

### ISSUE THREAD

**Issue by snehring** [warewulf/warewulf#1146]
### Steps to reproduce

configure warewulf for dnsmasq and have warewulf generate its config
```console
wwctl configure --all
```
attempt to boot a node you've configured

node will constantly pull the ipxe image seemingly because of order of dhcp-boot directives in dnsmasq config, moving `dhcp-boot=tag:iPXE` after the `dhcp-boot=tag:x86PC` directive seems to resolve it. 

I'm assuming dnsmasq resets the dhcp-boot for a client on subsequent matches, so ipxe should come last.

### Error message

No real error messages happen, the node just boots in a loop forever.

### Information on your system

wwctl version:   4.5.0-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.0-1"

NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@griznog I'm putting your name on this since you have the most dnsmasq experience. There's already a PR, and I'd be interested to get your review on the change.
