### ISSUE TITLE
Rocky 9 quickStart install documentation missing ipxe-bootimgs dependency

### ISSUE THREAD

**Issue by gmfricke** [warewulf/warewulf#1152]
https://warewulf.org/docs/development/quickstart/el9.html starts with:

```
sudo dnf groupinstall "Development Tools"
sudo dnf install epel-release
sudo dnf config-manager --set-enabled crb
sudo dnf install golang tftp-server dhcp-server nfs-utils gpgme-devel libassuan-devel
```

but this will lead to 

`wwctl configure tftp` later in the instructions being unable to find any boot loaders.

modifying 

`sudo dnf install golang tftp-server dhcp-server nfs-utils gpgme-devel libassuan-devel`

to

`sudo dnf install golang tftp-server dhcp-server nfs-utils gpgme-devel libassuan-devel ipxe-bootimgs`

would fix the problem.

I hit the "edit" button on the documentation page, but that threw me to a 404 page and so I am submitting the issue here.

Thanks, Matthew

**Comment by anderbubble** [comment]
@gmfricke the `development` branch of the documentation is replaced by the `main` branch. The updated quickstart guide is at https://warewulf.org/docs/main/quickstart/el.html

How did you end up there? (I'm expecting a Google search pointed you to it directly?)

**Comment by anderbubble** [comment]
Fixed in main.
