### ISSUE TITLE
install opensuse rpm failed 

### ISSUE THREAD

**Issue by aspfate** [warewulf/warewulf#1169]
### Steps to reproduce

```wget https://github.com/warewulf/warewulf/releases/download/v4.5.0/warewulf-4.5.0-1.suse.lp155.x86_64.rpm -O /tmp/warewulf.rpm && rpm -i --nodeps /tmp/warewulf.rpm```

### Error message

```
2fc55eb71c9f:/ # rpm -i --nodeps /tmp/warewulf.rpm
/var/tmp/rpm-tmp.fRKUdj: line 3: yq: command not found
error: %prein(warewulf-4.5.0-1.suse.lp155.x86_64) scriptlet failed, exit status 127
error: warewulf-4.5.0-1.suse.lp155.x86_64: install failed


2fc55eb71c9f:/tmp # rpm -qp --scripts warewulf.rpm | head -n 9
preinstall scriptlet (using /bin/sh):
getent group warewulf >/dev/null || groupadd -r warewulf
# use ipxe images from the distribution
yq e '
  .tftp.ipxe."00:00" = "undionly.kpxe" |
  .tftp.ipxe."00:07" = "ipxe-x86_64.efi" |
  .tftp.ipxe."00:09" = "ipxe-x86_64.efi" |
  .tftp.ipxe."00:0B" = "snp-arm64.efi" ' \
  -i /builddir/build/BUILDROOT/warewulf-4.5.0-1.suse.lp155.x86_64/etc/warewulf/warewulf.conf
```

1. yq is not in dep list

```
2fc55eb71c9f:/tmp # rpm -i warewulf.rpm 
error: Failed dependencies:
        dhcp-server is needed by warewulf-4.5.0-1.suse.lp155.x86_64
        firewalld is needed by warewulf-4.5.0-1.suse.lp155.x86_64
        ipxe-bootimgs is needed by warewulf-4.5.0-1.suse.lp155.x86_64
        nfs-kernel-server is needed by warewulf-4.5.0-1.suse.lp155.x86_64
        tftp is needed by warewulf-4.5.0-1.suse.lp155.x86_64
```

2. `/builddir/build/BUILDROOT/warewulf-4.5.0-1.suse.lp155.x86_64/etc/warewulf/warewulf.conf` is build stage path

### Information on your system

```
2fc55eb71c9f:/tmp # cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@mslacken can you confirm?

**Comment by mslacken** [comment]
I can confirm this bug. 

There are two solutions for this issue:
1. For openSUSE based distributions I generally advise to use the `warewulf4` package from the distribution itself. Backports and up to date versions are also provided in the [cluster:network](https://build.opensuse.org/project/show/network:cluster) project.
With following steps you can install warewulf4 from this project
```
zypper ar https://download.opensuse.org/repositories/network:/cluster/15.5/network:cluster.repo
zypper ref
zypper in warewulf4
```
2. Download the package via curl/wget. Install it with `zypper in yq warewulf-4.5.0-1.suse.lp155.x86_64.rpm` which will install all the dependencies, but will fail to install the package itself. After that you can install the package with `rpm -i --noscripts warewulf-4.5.0-1.suse.lp155.x86_64.rpm`. Now you will have to replace the ipxe binary paths in `warewulf.conf` with
```
yq e '
  .tftp.ipxe."00:00" = "undionly.kpxe" |
  .tftp.ipxe."00:07" = "ipxe-x86_64.efi" |
  .tftp.ipxe."00:09" = "ipxe-x86_64.efi" |
  .tftp.ipxe."00:0B" = "snp-arm64.efi" ' -i /etc/warewulf/warewulf.conf
  ```
