### ISSUE TITLE
Better FIPS Support in SSH key selection

### ISSUE THREAD

**Issue by AstroBacon** [warewulf/warewulf#1185]
### Summary

We are trying to use Warewulf 4 on a FIPS enabled system. When we run a wwctl configure --all there is a failure due to DSA being disabled in FIPS.

Can this be changed to a soft warning or remove DSA?

Specifically:
https://github.com/warewulf/warewulf/blob/main/internal/pkg/configure/ssh.go#L26

### Rationale

When we run a wwctl configure --all there is a failure due to DSA being disabled in FIPS.

wwctl configure --all
Building overlay for warewulf-001.local: host
Enabling and restarting the DHCP services
Building overlay for warewulf-001.local: host
Enabling and restarting the NFS services
Updating system keys
Skipping, key already exists: ssh_host_rsa_key
Setting up key: ssh_host_dsa_key
DSA keys are not allowed in FIPS mode
ERROR  : Failed to exec ssh-keygen: exit status 255
ERROR  : failed to exec ssh-keygen command: exit status 255

### Description

Can this be changed to a soft warning or remove DSA?
Perhaps replace the "exit 255" with "reply_warn"?

### Additional information

https://github.com/warewulf/warewulf/blob/main/internal/pkg/configure/ssh.go#L26
as well as a few other places I believe.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by MatthewHink** [comment]
Also this should be a hard error on FIPS. The problem is DSA.

**Comment by AstroBacon** [comment]
I think ed25519 is also not FIPS compliant, so that will likely fail as well.

**Comment by mslacken** [comment]
As work around, you don't need to call `wwctl configure ssh`, just call
```
wwctl configure dhcp
wwctl configure hostfile
wwctl configure nfs
wwctl configure tftp
```
and create the ssh-keys and add them to the `authorized_keys` of the root user.
