### ISSUE TITLE
wwctl configure all doesn't configure ssh

### ISSUE THREAD

**Issue by mslacken** [warewulf/warewulf#1230]
### Steps to reproduce

```
wwctl configure -a 
```
`SSH()` is called without argument, but with 
```
wwctl configure ssh
````
we call `configure.SSH(keyTypes...)`

# Version
wwctl version:	 4.5.2-1

**Comment by JATippit** [comment]
I'm having a similar issue - it appears the templates in /var/lib/warewulf/overlays/wwinit/rootfs/etc/ssh reference a local "keys" folder.  I believe this is referencing /etc/warewulf/keys.  Updating the files on the headnode to the full path fixes this for me.

**Comment by anderbubble** [comment]
#1187 added the ability to configure which ssh key types to build, and (when running `wwctl configure ssh` defaults to reading the desired key types from the configuration; but `wwctl configure --all` was missed, and doesn't pass the configured set of key types.

#1231 resolves this by passing the configured key types during `wwctl configure --all`.
