### ISSUE TITLE
Overlays are not rebuild after rebooting a node even if autobuild overlays: true

### ISSUE THREAD

**Issue by conxuro** [warewulf/warewulf#1240]
### Steps to reproduce

Making any change in the image or node definition that is set or used by any system overlay it is not reflected after a reboot, even if the autobuild overlays is set as true in warewulf.conf
For example, changing the container value of a node, is not reflected in /etc/issue after rebooting and loading the new container image.

### Error message

No error shown.

### Information on your system

```
wwctl version:   4.5.2-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.2-1"

NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@JasonYangShadow can you look into this and #1216?
