### ISSUE TITLE
node list -a output have excessive line spacing

### ISSUE THREAD

**Issue by severgun** [warewulf/warewulf#1241]
### Steps to reproduce

If there is a line of parameters that is wrapped around into multiple lines all other lines will have empty spacing for no reason.

```
wwctl node add node01
wwctl node set -A "this is very long string that contain a lot of kernel args so they are wrapped in multiple lines on node list --all output" node01
wwctl node list node01 -a
```

### Information on your system

NAME=“Rocky Linux”
VERSION=“8.9 (Green Obsidian)”
ID=“rocky”
ID_LIKE=“rhel centos fedora”
VERSION_ID=“8.9”
PLATFORM_ID=“platform:el8”
PRETTY_NAME=“Rocky Linux 8.9 (Green Obsidian)”
ANSI_COLOR=“0;32”
LOGO=“fedora-logo-icon”
CPE_NAME=“cpe:/o:rocky:rocky:8:GA”
HOME_URL=“[https://rockylinux.org/ 1](https://rockylinux.org/)”
BUG_REPORT_URL=“https://bugs.rockylinux.org/”
SUPPORT_END=“2029-05-31”
ROCKY_SUPPORT_PRODUCT=“Rocky-Linux-8”
ROCKY_SUPPORT_PRODUCT_VERSION=“8.9”
REDHAT_SUPPORT_PRODUCT=“Rocky Linux”
REDHAT_SUPPORT_PRODUCT_VERSION=“8.9”

wwctl version: 4.5.2-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.2-1"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by pavalenta** [comment]
Also appears to be a new line created between each output for all nodes which extends the console

**Comment by griznog** [comment]
Workaround:

```
wwctl node list -a | sed  's/[[:space:]]*$//g'
```
