### ISSUE TITLE
Provided iPXE 1.0.0 does not work with I350 intel nic

### ISSUE THREAD

**Issue by severgun** [warewulf/warewulf#1242]
### Steps to reproduce

Try to boot. Get Network Unreachable
set net0/ip does not help. dhcp command does not help

I tried ipxe.iso from ipxe.org as kickstarter and it works. iPXE version in iso is 1.21.1+

### Information on your system

NAME=“Rocky Linux”
VERSION=“8.9 (Green Obsidian)”
ID=“rocky”
ID_LIKE=“rhel centos fedora”
VERSION_ID=“8.9”
PLATFORM_ID=“platform:el8”
PRETTY_NAME=“Rocky Linux 8.9 (Green Obsidian)”
ANSI_COLOR=“0;32”
LOGO=“fedora-logo-icon”
CPE_NAME=“cpe:/o:rocky:rocky:8:GA”
HOME_URL=“[https://rockylinux.org/ 1](https://rockylinux.org/)”
BUG_REPORT_URL=“[https://bugs.rockylinux.org/”](https://bugs.rockylinux.org/%E2%80%9D)
SUPPORT_END=“2029-05-31”
ROCKY_SUPPORT_PRODUCT=“Rocky-Linux-8”
ROCKY_SUPPORT_PRODUCT_VERSION=“8.9”
REDHAT_SUPPORT_PRODUCT=“Rocky Linux”
REDHAT_SUPPORT_PRODUCT_VERSION=“8.9”

wwctl version: 4.5.2-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.2-1"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
Warewulf no longer ships iPXE. By default it uses the iPXE that comes with your host OS, but you can also (as you have suggested here) build or bring your own iPXE. We supply a helper script for doing so at https://github.com/warewulf/warewulf/blob/main/scripts/build-ipxe.sh
