### ISSUE TITLE
Broken symlinks at root are skipped during container build

### ISSUE THREAD

**Issue by lebonez** [warewulf/warewulf#1267]
https://github.com/warewulf/warewulf/blob/630156d51403bf28d9d293330cc9d22229aee128/internal/pkg/util/util.go#L301

Often in node boot images, we do have some symlinks in `/` that are broken until the node boots and is mounted. This line is preventing those symlinks from ending up in the image. Was there a reason for skipping broken symlinks on `/`?

As an example, one might have a symlink like `/public` located in `/` like below, but `/data1/public` won't be available until the Lustre filesystem mounts.
`public -> /data1/public`

It seems the current work around might be to have the broken symlinks in an image's root directory to exist on the warewulf build host but this seems clunky.

**Comment by anderbubble** [comment]
Thanks for submitting the issue, and for identifying the likely place in the code. Should be a relatively straightforward fix; but we'll investigate and let you know if we have any further questions.

**Comment by anderbubble** [comment]
I think we just need to change `os.Stat` to `os.Lstat` at https://github.com/warewulf/warewulf/blob/630156d51403bf28d9d293330cc9d22229aee128/internal/pkg/util/util.go#L300

But I'll have to test that.

**Comment by lebonez** [comment]
Thank you, yes that would likely be all that is needed in our case.
