### ISSUE TITLE
wwctl node set --hwaddr too strict

### ISSUE THREAD

**Issue by posch** [warewulf/warewulf#1293]
### Steps to reproduce

```
wwctl node set -H 44:11:c:ae:43:b2 testnode
ERROR: address 44:11:c:ae:43:b2: invalid MAC address
```

The issue is the missing leading 0 in the third octet.

Although one may find it unusal to write a MAC address without leading zeros, this is what you get from

```
# getent ethers testnode
44:11:c:ae:43:b2 testnode
```

although /etc/ethers has the leading zero:

```
44:11:0c:ae:43:b2 testnode
```

### Error message

```
ERROR: address 44:11:c:ae:43:b2: invalid MAC address
```

### Information on your system

```
wwctl version:   4.5.4+7.g77159d73-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.4+7.g77159d73-1"
```

Rocky Linux release 9.4 (Blue Onyx)

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
This change has been declined by golang at https://github.com/golang/go/issues/68321
