### ISSUE TITLE
wwctl kernel import do import image to the wrong path

### ISSUE THREAD

**Issue by edvinas31** [warewulf/warewulf#1300]
### Steps to reproduce

```wwctl kernel import $(uname -r)```

Image is imported successfully, but in a wrong directory (/var/lib/warewulf/provision/overlays/kernel/), because warewulf cannot apply that image into the nodes and it tries to find images under /var/lib/warewulf/provision/kernel/

### Information on your system

```wwctl version```
4.5.4
```/etc/os-release```
8.10 Rocky Linux

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@JasonYangShadow can you look into this?

**Comment by JasonYangShadow** [comment]
@edvinas31 cc @anderbubble 
I tested on the rockylinux 8.10
```
[root@localhost vagrant]# wwctl container list
  CONTAINER NAME  NODES  KERNEL VERSION               CREATION TIME        MODIFICATION TIME    SIZE
  rocky-8         0      4.18.0-513.9.1.el8_9.x86_64  11 Jul 24 07:19 UTC  01 Jan 70 00:00 UTC  1.2 GiB

[root@localhost vagrant]# wwctl kernel import $(uname -r)
Found kernel at: /boot/vmlinuz-4.18.0-553.8.1.el8_10.x86_64
Created image for 4.18.0-553.8.1.el8_10.x86_64 drivers: /var/lib/warewulf/provision/kernel/4.18.0-553.8.1.el8_10.x86_64/kmods.img
Compressed image for 4.18.0-553.8.1.el8_10.x86_64 drivers: /var/lib/warewulf/provision/kernel/4.18.0-553.8.1.el8_10.x86_64/kmods.img.gz
4.18.0-553.8.1.el8_10.x86_64: Finished kernel build

[root@localhost vagrant]# ls -al /var/lib/warewulf/provision/
total 0
drwxr-xr-x. 3 root root     20 Jul 11 07:54 .
drwxr-xr-x. 5 root warewulf 54 Jul 11 07:54 ..
drwxr-xr-x. 3 root root     42 Jul 11 07:54 kernel

[root@localhost vagrant]# ls -al /var/lib/warewulf/provision/kernel/
total 0
drwxr-xr-x. 3 root root 42 Jul 11 07:54 .
drwxr-xr-x. 3 root root 20 Jul 11 07:54 ..
drwxr-xr-x. 2 root root 73 Jul 11 07:55 4.18.0-553.8.1.el8_10.x86_64

[root@localhost vagrant]# ls -al /var/lib/warewulf/provision/kernel/4.18.0-553.8.1.el8_10.x86_64/
total 2076544
drwxr-xr-x. 2 root root         73 Jul 11 07:55 .
drwxr-xr-x. 3 root root         42 Jul 11 07:54 ..
-rw-r--r--. 1 root root 1408888320 Jul 11 07:55 kmods.img
-rw-r--r--. 1 root root  706610373 Jul 11 07:55 kmods.img.gz
-rw-r--r--. 1 root root         28 Jul 11 07:55 version
-rwxr-xr-x. 1 root root   10873160 Jul 11 07:54 vmlinuz

[root@localhost vagrant]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"

[root@localhost vagrant]# wwctl version
wwctl version:   4.5.4-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.4-1"
```

can you show more info on reproducing the issue? Thanks!

**Comment by edvinas31** [comment]
Sure. Sending the output
![image](https://github.com/warewulf/warewulf/assets/49708029/1527ba04-b329-4497-80ac-ce4c566b5a05)

**Comment by JasonYangShadow** [comment]
> Sure. Sending the output ![image](https://private-user-images.githubusercontent.com/49708029/347847326-1527ba04-b329-4497-80ac-ce4c566b5a05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MzAzOTIsIm5iZiI6MTcyMDczMDA5MiwicGF0aCI6Ii80OTcwODAyOS8zNDc4NDczMjYtMTUyN2JhMDQtYjMyOS00NDk3LTgwYWMtY2U0YzU2NmI1YTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIwMzQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYWYwZGU3ZGZjYWEyOGRmNjBlYmQyMGQ2OWI2ZmI2NTY4M2E0MzQzOGRmM2JhODkzNmFiOWI1NjQyYzRmYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sv8oEtbf8SOkMeeWwrkaaENSQoLJREVtgF-x1iFrkk4)

thanks so much for the screenshot. 
I checked the source code,  the kernel import destination is calculated by 
https://github.com/warewulf/warewulf/blob/1e17b816c5e8d3a33d4f43d3407e38aecb22b0d2/internal/pkg/kernel/kernel.go#L39
can you run the following command and print out the warewulf conf
```
 wwctl genconfig warewulfconf print
```
or
check the config file `/etc/warewulf/warewulf.conf`
to see if the `wwprovisiondir` is `/var/lib/warewulf/provision` for example.

```
...
paths:
  bindir: /usr/bin
  sysconfdir: /etc
  localstatedir: /var/lib
  ipxesource: /usr/share/ipxe
  srvdir: /var/lib
  firewallddir: /usr/lib/firewalld/services
  systemddir: /usr/lib/systemd/system
  wwoverlaydir: /var/lib/warewulf/overlays
  wwchrootdir: /var/lib/warewulf/chroots
  wwprovisiondir: /var/lib/warewulf/provision
  wwclientdir: /warewulf
```

**Comment by edvinas31** [comment]
Hi, this is my warewulf.conf

***@***.*** edvinas]# wwctl genconfig warewulfconf print

WW_INTERNAL: 45

ipaddr: 10.2.1.1

netmask: 255.255.255.0

network: 10.2.1.0

warewulf:

  port: 9873

  secure: false

  update interval: 60

  autobuild overlays: true

  host overlay: true

  syslog: false

  datastore: /usr/share

  grubboot: false

dhcp:

  enabled: true

  template: default

  range start: 10.2.1.11

  range end: 10.2.1.99

  systemd name: dhcpd

tftp:

  enabled: true

  tftproot: /var/lib/tftpboot

  systemd name: tftp

  ipxe:

    "00:00": undionly.kpxe

    "00:07": ipxe-snponly-x86_64.efi

    "00:09": ipxe-snponly-x86_64.efi

    00:0B: arm64-efi/snponly.efi

nfs:

  enabled: false

  export paths: []

  systemd name: nfsd

ssh:

  key types:

  - rsa

  - dsa

  - ecdsa

  - ed25519

container mounts:

- source: /etc/resolv.conf

  dest: /etc/resolv.conf

  readonly: true

paths:

  bindir: /usr/bin

  sysconfdir: /etc

  localstatedir: /var/lib

  ipxesource: /usr/share/ipxe

  srvdir: /var/lib

  firewallddir: /usr/lib/firewalld/services

  systemddir: /usr/lib/systemd/system

  wwoverlaydir: /var/lib/warewulf/overlays

  wwchrootdir: /var/lib/warewulf/chroots

  wwprovisiondir: /var/lib/warewulf/provision/overlays

  wwclientdir: /warewulf


Please be aware that first I installed warewulf 4.4.0 from source and only
now was updating to 4.5.4 using package (rpm) method.

fre. 12. jul. 2024 kl. 00.00 skrev Xu YANG ***@***.***>:

**Comment by JasonYangShadow** [comment]
> wwprovisiondir: /var/lib/warewulf/provision/overlays

thanks so much! as you can see, the value for `wwprovisiondir` is `/var/lib/warewulf/provision/overlays`, that is the reason why kernel images are generated and copied to the `wrong overlays folder`, I suggest restoring it to `/var/lib/warewulf/provision`. 

cc @anderbubble not sure but is it possible that this `provisiondir` is somehow changed by warewulf and not by users manually ?

**Comment by anderbubble** [comment]
I don't have any kind of internal explanation for why `wwprovisiondir` would be set to `/var/lib/warewulf/provision/overlays`, but suspect that it must be related to the indicated prior source-based deployment and configuration selected at that time.

Still, @JasonYangShadow, shouldn't warewulf then look for kernels in the same place it provisioned them? This may be a strange / unusual / non-default location for kernels to be; but it should still then be able to retrieve them from that location.

**Comment by JasonYangShadow** [comment]
> I don't have any kind of internal explanation for why `wwprovisiondir` would be set to `/var/lib/warewulf/provision/overlays`, but suspect that it must be related to the indicated prior source-based deployment and configuration selected at that time.
> 
> Still, @JasonYangShadow, shouldn't warewulf then look for kernels in the same place it provisioned them? This may be a strange / unusual / non-default location for kernels to be; but it should still then be able to retrieve them from that location.

as far as I checked the source code, (might be wrong) when provisioning kernel, it might (possibly) reach out to different branches when container name is set and kernel override is not set
https://github.com/warewulf/warewulf/blob/1e17b816c5e8d3a33d4f43d3407e38aecb22b0d2/internal/pkg/warewulfd/provision.go#L118
