### ISSUE TITLE
Add logrotate rules to packaged distributives

### ISSUE THREAD

**Issue by severgun** [warewulf/warewulf#1311]
### Summary

Would be nice to have basic log rotation rules for `/var/log/warewulfd.log` in rpms

### Rationale

Log can grow quite a lot over time.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mslacken** [comment]
Thanks for reporting, there is already a PR for this, see #1276 you can use the configuration file from there.
