### ISSUE TITLE
Unable to update overlay file

### ISSUE THREAD

**Issue by dacianstremtan** [warewulf/warewulf#1312]
### Steps to reproduce

I am trying to edit an overlay file:

`wwctl overaly edit generic /etc/fstab.ww`

### Error message

`ERROR  : Unable to update /var/lib/warewulf/overlays/generic/rootfs/etc/fstab.ww: rename /tmp/ww-overlay-edit-3137351506 /var/lib/warewulf/overlays/generic/rootfs/etc/fstab.ww: invalid cross-device link`

### Information on your system

the /var/lib/warewulf and /tmp are on separate partitions

mount output for relevant mount points
`tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime,seclabel)`
`/dev/sda12 on /var/lib/warewulf type xfs (rw,nosuid,nodev,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,noquota)`

[root@master2 ~]# wwctl version
wwctl version:	 4.5.5-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.5-1"

[root@master2 ~]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@JasonYangShadow could you look into this?

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow could you look into this?

ahh, my bad, os.rename only works on the same partition, should consider the case that tmpfs and wwctl exist on different partitions.
