### ISSUE TITLE
Possible bug in 4.5.5 regarding adding local users to a container

### ISSUE THREAD

**Issue by gzcwnk** [warewulf/warewulf#1318]
### Steps to reproduce

wwctl container syncuser --write rocky-8
WARN   : id(998) collision: host(chrony) container(unbound)
WARN   : add unbound to host to resolve conflict
ERROR  : Error in synchronize: id(998) collision: host(chrony) container(unbound)

### Error message

as above

### Information on your system

[root@vuwunicoglbhpc3 ~]# uname -a
Linux vuwunicoglbhpc3.ods.vuw.ac.nz 5.14.0-427.26.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 5 11:34:54 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
[root@vuwunicoglbhpc3 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 9.4 (Plow)
[root@vuwunicoglbhpc3 ~]#

[root@vuwunicoglbhpc3 ~]# wwctl version
wwctl version:   4.5.5-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.5-1"
[root@vuwunicoglbhpc3 ~]#

[root@vuwunicoglbhpc3 log]# cat warewulfd.log
[Tue Jul 30 13:08:50 NZST 2024] WARN   : Received SIGHUP, reloading...
[Tue Jul 30 13:16:24 NZST 2024] RECV   : hwaddr: 00:50:56:8d:15:85, ipaddr: 130.195.87.101:53145, stage: ipxe
[Tue Jul 30 13:16:24 NZST 2024] WARN   : 00:50:56:8d:15:85 (node not configured)
No node found
[Tue Jul 30 13:16:24 NZST 2024] ERROR  : 00:50:56:8d:15:85 (unknown/unconfigured node)
[Tue Jul 30 13:16:24 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:16:24 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:17:50 NZST 2024] RECV   : hwaddr: 00:50:56:8d:15:85, ipaddr: 130.195.87.101:40430, stage: ipxe
[Tue Jul 30 13:17:50 NZST 2024] WARN   : 00:50:56:8d:15:85 (node not configured)
No node found
[Tue Jul 30 13:17:50 NZST 2024] ERROR  : 00:50:56:8d:15:85 (unknown/unconfigured node)
[Tue Jul 30 13:17:50 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:17:50 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:19:17 NZST 2024] RECV   : hwaddr: 00:50:56:8d:15:85, ipaddr: 130.195.87.101:41359, stage: ipxe
[Tue Jul 30 13:19:17 NZST 2024] WARN   : 00:50:56:8d:15:85 (node not configured)
No node found
[Tue Jul 30 13:19:17 NZST 2024] ERROR  : 00:50:56:8d:15:85 (unknown/unconfigured node)
[Tue Jul 30 13:19:17 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:19:17 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:20:43 NZST 2024] RECV   : hwaddr: 00:50:56:8d:15:85, ipaddr: 130.195.87.101:27696, stage: ipxe
[Tue Jul 30 13:20:43 NZST 2024] WARN   : 00:50:56:8d:15:85 (node not configured)
No node found
[Tue Jul 30 13:20:43 NZST 2024] ERROR  : 00:50:56:8d:15:85 (unknown/unconfigured node)
[Tue Jul 30 13:20:43 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:20:43 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:22:40 NZST 2024] RECV   : hwaddr: 00:50:56:8d:15:85, ipaddr: 130.195.87.101:3270, stage: ipxe
[Tue Jul 30 13:22:40 NZST 2024] WARN   : 00:50:56:8d:15:85 (node not configured)
No node found
[Tue Jul 30 13:22:40 NZST 2024] ERROR  : 00:50:56:8d:15:85 (unknown/unconfigured node)
[Tue Jul 30 13:22:40 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:22:40 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:22:42 NZST 2024] RECV   : hwaddr: 00:50:56:8d:49:63, ipaddr: 130.195.87.103:3262, stage: ipxe
[Tue Jul 30 13:22:42 NZST 2024] WARN   : 00:50:56:8d:49:63 (node not configured)
No node found
[Tue Jul 30 13:22:42 NZST 2024] ERROR  : 00:50:56:8d:49:63 (unknown/unconfigured node)
[Tue Jul 30 13:22:42 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:22:42 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:24:06 NZST 2024] RECV   : hwaddr: 00:50:56:8d:15:85, ipaddr: 130.195.87.101:1414, stage: ipxe
[Tue Jul 30 13:24:06 NZST 2024] WARN   : 00:50:56:8d:15:85 (node not configured)
No node found
[Tue Jul 30 13:24:06 NZST 2024] ERROR  : 00:50:56:8d:15:85 (unknown/unconfigured node)
[Tue Jul 30 13:24:06 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:24:06 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:24:09 NZST 2024] RECV   : hwaddr: 00:50:56:8d:49:63, ipaddr: 130.195.87.103:52001, stage: ipxe
[Tue Jul 30 13:24:09 NZST 2024] WARN   : 00:50:56:8d:49:63 (node not configured)
No node found
[Tue Jul 30 13:24:09 NZST 2024] ERROR  : 00:50:56:8d:49:63 (unknown/unconfigured node)
[Tue Jul 30 13:24:09 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:24:09 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:25:32 NZST 2024] RECV   : hwaddr: 00:50:56:8d:15:85, ipaddr: 130.195.87.101:41843, stage: ipxe
[Tue Jul 30 13:25:32 NZST 2024] WARN   : 00:50:56:8d:15:85 (node not configured)
No node found
[Tue Jul 30 13:25:32 NZST 2024] ERROR  : 00:50:56:8d:15:85 (unknown/unconfigured node)
[Tue Jul 30 13:25:32 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:25:32 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:25:35 NZST 2024] RECV   : hwaddr: 00:50:56:8d:49:63, ipaddr: 130.195.87.103:9055, stage: ipxe
[Tue Jul 30 13:25:35 NZST 2024] WARN   : 00:50:56:8d:49:63 (node not configured)
No node found
[Tue Jul 30 13:25:35 NZST 2024] ERROR  : 00:50:56:8d:49:63 (unknown/unconfigured node)
[Tue Jul 30 13:25:35 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:25:35 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:43:23 NZST 2024] RECV   : hwaddr: 00:50:56:8d:49:63, ipaddr: 130.195.87.103:17945, stage: ipxe
[Tue Jul 30 13:43:23 NZST 2024] WARN   : 00:50:56:8d:49:63 (node not configured)
No node found
[Tue Jul 30 13:43:23 NZST 2024] ERROR  : 00:50:56:8d:49:63 (unknown/unconfigured node)
[Tue Jul 30 13:43:23 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:43:23 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[Tue Jul 30 13:43:26 NZST 2024] RECV   : hwaddr: 00:50:56:8d:15:85, ipaddr: 130.195.87.101:48146, stage: ipxe
[Tue Jul 30 13:43:26 NZST 2024] WARN   : 00:50:56:8d:15:85 (node not configured)
No node found
[Tue Jul 30 13:43:26 NZST 2024] ERROR  : 00:50:56:8d:15:85 (unknown/unconfigured node)
[Tue Jul 30 13:43:26 NZST 2024] SERV   : stage_file '/etc/warewulf/ipxe/unconfigured.ipxe'
[Tue Jul 30 13:43:26 NZST 2024] SEND   :                : /etc/warewulf/ipxe/unconfigured.ipxe
[root@vuwunicoglbhpc3 log]#

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@gzcwnk I think this is normal, and the message is just confusing. I added additional help text in this event in #1383, which is now available in v4.5.7. But let me know if you're still having an issue.
