### ISSUE TITLE
fix autodetected kernel sorting

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#1332]
### Steps to reproduce

Warewulf does not reliably detect the most recent kernel during auto-detection.

According to @griznog:

> I'm having a faint recollection that my original problem
> seemed to be that the kernel autodetection acted as if it was sorting
> the kernel numerically to find the latest instead of the sort -V
> equivalent.

### Information on your system

```
$ wwctl version
wwctl version:	 4.5.1test1+129.gf2213f0e.dirty-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.1test1+129.gf2213f0e.dirty-1"
```

```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by JasonYangShadow** [comment]
@anderbubble sorry that I do not fully understand the context here, is the issue related to `wwctl kernel list` command? what is the context of auto kernel detection ?

**Comment by anderbubble** [comment]
Not `wwctl kernel list`; the issue is that `wwctl server` / warewulfd sometimes selects the wrong kernel when no kernel is specified. There is a theory that it's lexically sorting the kernel version number, rather than using a version comparison library to get the newest kernel available in the image. (We may also want to explicitly filter out "rescue" kernels.)
