### ISSUE TITLE
container exec --syncuser does not actually run syncuser

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#1344]
### Steps to reproduce

```
# wwctl container exec --syncuser rocky-9.3 '/bin/id'
uid=0(root) gid=0(root) groups=0(root)

The Rocky Linux community provides updates for the latest point release of
Rocky Linux 9. If you need to remain on a specific point release (e.g., Rocky
Linux 9.2) you may want to engage with a commercial support provider for
long-term support.

https://rockylinux.org/support

+ dnf clean all
0 files removed
Rebuilding container...
Created image for VNFS container rocky-9.3: /var/lib/warewulf/provision/container/rocky-9.3.img
Compressed image for VNFS container rocky-9.3: /var/lib/warewulf/provision/container/rocky-9.3.img.gz
```

### Error message

[none]

### Information on your system

```
$ wwctl version
wwctl version:	 4.5.1test1+129.gf2213f0e.dirty-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.1test1+129.gf2213f0e.dirty-1"
```

```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by JasonYangShadow** [comment]
I will take a look at this issue. @anderbubble if there are other high priority issues, feel free to assign to me

**Comment by JasonYangShadow** [comment]
@anderbubble 
I checked the source code and there are several points needing to be clarified before asking for the review
1. To trigger the `SyncUids` function it requires both `userdbChanged && SyncUser`.
https://github.com/warewulf/warewulf/blob/09c17551e869deb7403bf277905c397870026ae6/internal/app/wwctl/container/exec/main.go#L125
2. `/bin/id` will not update the `ctime`. (It only updates the `atime`?) `permission` (or metadata) changes will update the `ctime`,  here I think should we use `mtime` here? (reflecting the data changes ?)
https://github.com/warewulf/warewulf/blob/09c17551e869deb7403bf277905c397870026ae6/internal/app/wwctl/container/exec/main.go#L146
3. `shell` can also add `--syncuser` flag and as it calls `exec` sub-command, test can be done as the following
![image](https://github.com/user-attachments/assets/53ecd3e7-b373-47f1-a61c-75c9a56fb1c8)

**Comment by anderbubble** [comment]
I realize now that my initial bug report is wrong. I just tried running _without_ #1358, and it works, so long as I modify `/etc/passwd`.

```
wwctl container exec --syncuser rocky-9.3 -- -- /bin/bash -c 'echo "" >>/etc/passwd'
```

That said, I like adding `--syncuser` to shell as in #1358, and the change to `mtime` also in #1358; so I'm going to close this issue but keep the PR.
