### ISSUE TITLE
wwctl container syncuser --write  rocky-8 fails

### ISSUE THREAD

**Issue by gzcwnk** [warewulf/warewulf#1353]
### Steps to reproduce

wwctl container syncuser --write  rocky-8

In order to sync uids and gids between RHEL9.4 host and rocky8 container.  Specifically slurm and munge

### Error message

WARN   : id(998) collision: host(chrony) container(unbound)
WARN   : add unbound to host to resolve conflict
ERROR  : Error in synchronize: id(998) collision: host(chrony) container(unbound)
[root@vuwunicoglbhpc3 admjonesst1]#

### Information on your system

[root@vuwunicoglbhpc3 admjonesst1]# wwctl version
wwctl version:   4.5.5-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.5-1"
[root@vuwunicoglbhpc3 admjonesst1]#

[root@vuwunicoglbhpc3 admjonesst1]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.4 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.4 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
[root@vuwunicoglbhpc3 admjonesst1]#

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
This is not a bug in Warewulf: syncuser can't synchronize with the available information between your host and container.

As indicated by the warning, to synchronize you need to add an "unbound" user to the host so that syncuser knows what id to use for unbound.

**Comment by gzcwnk** [comment]
Can you improve the failure message then please as it is unclear from the error produced what to do.
