### ISSUE TITLE
Quickstart guide missing 2 important pieces

### ISSUE THREAD

**Issue by gzcwnk** [warewulf/warewulf#1355]
### Steps to reproduce

There is no mention in the quickstart guide that the unbound user (plus settings like login or not) needs to be added to the host server.
Secondly that the overlay command needs to be run,  wwctl overlay build  or nodes will not boot.

### Error message

as above

### Information on your system

[root@vuwunicoglbhpc3 ~]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.4 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.4 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
[root@vuwunicoglbhpc3 ~]#

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
The "unbound" user needing to be created is an aspect of your local environment as compared to the container image you are using. It is not a Warewulf issue.

Running "overlay build" should no longer be required as of v4.5.6, as autobuild has been fixed to work in the common case by #1301.
