### ISSUE TITLE
Provisioning via infiniband

### ISSUE THREAD

**Issue by HaroldoUFRN** [warewulf/warewulf#1368]
### Summary

Currently, Warewulf provisioning works on ethernet. 
Infiniband cards run PXE software at boot as well, so provisioning via infiniband is possible but unimplemented.

### Rationale

There are two main expected advantage is performance, as booting many nodes connected to infiniband network at the same time would be faster and would not slow down the main administrative ethernet network.

### Description

Maybe allowing infiniband hardware addresses with `wwctl node set --hwaddr` would suffice. 
Howerver, after some initial reading and testing, I belive infiniband cards wont even send dhcp option hardware during dhcp queries. Instead, they will send dhcp option dhcp-client-identifier.

### Additional information

Mellanox cards run ipxe software at boot.
This is not about setting infiniband cards to ethernet mode.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by griznog** [comment]
I currently boot nodes over both Infiniband and Ethernet, there's nothing special required beyond having DHPC working for the Infiniband fabric. That's trivial to do with DNSMasq, but I'm not sure it's as easy with dhcpd. I'd recommend making the switch to DNSMasq as the easiest solution and it's on the long term discussion/to-do (4.7+?) list to make DNSmasq the default DHCP provider for Warewulf once it's more polished.

**Comment by griznog** [comment]
Oh, one caveat is that ConnectX cards in IB mode withsome combination of settings, possibly Legacy BIOS or settings in the cards firmware will boot with a burned in iPXE stack that lacks needed support. At some point I worked around that but didnt' take enough notes to further describe it. Just be aware that the iPXE you see when booting may not have came from the Warewulf server.

**Comment by HaroldoUFRN** [comment]
How do you set the infiniband hardware address?

**Comment by griznog** [comment]
Depending on what is doing it, card firmware vs operating systemvs any particular dhcp client, an IB card can present itself in at least three ways, an example from one of my nodes for DNSMasq is the `dhcp-host` line:

98:03:9b:bb:6c:70,98:03:9b:03:00:bb:6c:70,id:20:00:03:95:fe:80:00:00:00:00:00:00:98:03:9b:03:00:bb:6c:70,set:stateful,100.64.31.3,fury,365d

The entries there are:
* 64 bit hwardd: `98:03:9b:03:00:bb:6c:70`
* 48 bit MAC hwadrr: `98:03:9b:bb:6c:70` 
    * Notice that is the 64 bit address less the two internal octets)
* Client ID: id:20:00:03:95:fe:80:00:00:00:00:00:00:98:03:9b:03:00:bb:6c:70 
    * This is maybe what you get from `ip -o link` but what I see on teh DHCP server doesn't always match that. I think how client ID is generated can vary by ConnectX card generation. I don't have a really good explantion for where this comes from, but I see it in requests.

You can probably ignore Client ID on newer cards, but at some point ConnectX3 or ConnectX4 I had to have it so I just contiue putting it in the config out of habit.

**Comment by HaroldoUFRN** [comment]
I know undestand that this is mostly a DHCP configuration matter. 
Also, I wasn't aware that the `--hwaddr` parameter accepts 64 bit values, so I no longer believe this is a feature to be added.

**Comment by anderbubble** [comment]
Great! Thanks for following-up!
