### ISSUE TITLE
error importing container with a name containing a colon

### ISSUE THREAD

**Issue by gzcwnk** [warewulf/warewulf#1371]
### Steps to reproduce

When I made a container name I used a : this caused the following error,

[root@vuwunicoslurmt1 rocky8-27-8-2024]# podman save rocky8:8.x > rocky8:8.x.tar

[root@vuwunicoslurmt1 rocky8-27-8-2024]#
[root@vuwunicoslurmt1 rocky8-27-8-2024]#
[root@vuwunicoslurmt1 rocky8-27-8-2024]# wwctl container import rocky8:8.x.tar rocky8:8.x
ERROR : could not import image: opening file "//root/podman/rocky8-27-8-2024/rocky8": open //root/podman/rocky8-27-8-2024/rocky8: no such file or directory
ERROR: could not import image: opening file "//root/podman/rocky8-27-8-2024/rocky8": open //root/podman/rocky8-27-8-2024/rocky8: no such file or directory
[root@vuwunicoslurmt1 rocky8-27-8-2024]# ls -l
total 2779820
-rw-r--r--. 1 root root 345 Aug 26 15:59 container_exit.sh
-rw-r--r--. 1 root root 1056 Aug 26 15:43 Containerfile
-rw-r--r--. 1 root root 24 Aug 26 15:53 excludes
-rw-r--r--. 1 root root 2846520320 Aug 26 16:22 rocky8:8.x.tar

renaming it,

mv rocky8:8.x.tar rocky8-8.x.tar
[root@vuwunicoslurmt1 rocky8-27-8-2024]# wwctl container import rocky8-8.x.tar rocky8:8.x
Copying blob f11c864af433 done |
8><----

and it seems to work fine, (nodes boot Ok off it)

### Error message

As above.

### Information on your system

[root@vuwunicoslurmt1 rocky8-27-8-2024]# wwctl version
wwctl version:	 4.5.6-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.6-1"
[root@vuwunicoslurmt1 rocky8-27-8-2024]# 

[root@vuwunicoslurmt1 rocky8-27-8-2024]# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
[root@vuwunicoslurmt1 rocky8-27-8-2024]# 

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
Thanks for moving this here, @gzcwnk!

**Comment by JasonYangShadow** [comment]
it is an upstream issue, colon is kind of restricted symbol inside the file/path name.
https://github.com/containers/image/blob/31d4ad14fe4da8ef3969ff67297831ab291c76f1/docker/archive/transport.go#L65
`refString here is the abs path, e.g. /home/vagrant/rocky8:8.x.tar`, it'll treat the file name as a image and a tag by splitting based on `:`. 
Also it is not recommended to create tar file using colon
https://github.com/containers/podman/issues/489
https://github.com/containers/podman/pull/694
