### ISSUE TITLE
Documentation clarification/expansion/fix

### ISSUE THREAD

**Issue by gzcwnk** [warewulf/warewulf#1373]
### Steps to reproduce

In the documentation,

https://warewulf.org/docs/v4.5.x/contents/disks.html

Requirements[](https://warewulf.org/docs/v4.5.x/contents/disks.html#requirements)

Partition and file system creation requires both ignition and sgdisk to be installed in the container image.
Rocky Linux[](https://warewulf.org/docs/v4.5.x/contents/disks.html#rocky-linux)

dnf install ignition gdisk

### Error message

[root@vuwunicoslurmt1 rocky8-27-8-2024]# dnf whatprovides ignition
Last metadata expiration check: 1:47:39 ago on Thu 29 Aug 2024 18:42:33 EDT.
Error: No Matches found
[root@vuwunicoslurmt1 rocky8-27-8-2024]# cat /etc/os
os-release  ostree/
[root@vuwunicoslurmt1 rocky8-27-8-2024]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
[root@vuwunicoslurmt1 rocky8-27-8-2024]#

[root@vuwunicoslurmt1 rocky8-27-8-2024]# yum repolist
repo id                              repo name
appstream                            Rocky Linux 8 - AppStream
baseos                               Rocky Linux 8 - BaseOS
epel                                 Extra Packages for Enterprise Linux 8 - x86_64
extras                               Rocky Linux 8 - Extras
powertools                           Rocky Linux 8 - PowerTools
[root@vuwunicoslurmt1 rocky8-27-8-2024]#

### Information on your system

[root@vuwunicoslurmt1 rocky8-27-8-2024]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
[root@vuwunicoslurmt1 rocky8-27-8-2024]#

[root@vuwunicoslurmt1 rocky8-27-8-2024]# yum repolist
repo id                              repo name
appstream                            Rocky Linux 8 - AppStream
baseos                               Rocky Linux 8 - BaseOS
epel                                 Extra Packages for Enterprise Linux 8 - x86_64
extras                               Rocky Linux 8 - Extras
powertools                           Rocky Linux 8 - PowerTools
[root@vuwunicoslurmt1 rocky8-27-8-2024]#

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by gzcwnk** [comment]
Should have been documentation but I cannot see how to do / change that  :(

**Comment by gzcwnk** [comment]
also error,  [root@vuwunicoslurmt1 rocky8-27-8-2024]# yum whatprovides gsdisk
Last metadata expiration check: 2:20:31 ago on Thu 29 Aug 2024 18:42:33 EDT.
Error: No Matches found
[root@vuwunicoslurmt1 rocky8-27-8-2024]#

**Comment by mslacken** [comment]
@anderbubble assigning this back to you, as I don't have a rocky machine at my hand.
