### ISSUE TITLE
wwctl command ERROR does not result in non-zero return code

### ISSUE THREAD

**Issue by epruesse** [warewulf/warewulf#1377]
### Steps to reproduce

```
$ wwctl container copy rockylinux-9 rockylinux-9-tmp
ERROR  : An other container with name: rockylinux-9-tmp already exists in sources.
$ echo $?
0
```

All `wwctl` commands should return non-zero on failure. Helps with scripting...

**Comment by anderbubble** [comment]
@JasonYangShadow can you work on this? I think you've done some of this already.
