### ISSUE TITLE
Add flag --build to wwctl container copy, default false

### ISSUE THREAD

**Issue by epruesse** [warewulf/warewulf#1378]
### Summary

Add flag `--no-build` to `wwctl container copy` that skips automatic container rebuild.  

### Rationale

The first thing anyone does after copying a container is surely making edits to it, so you'd almost never want to wait for the image build and compress steps at that point. Changing old behavior is perhaps suboptimal, but a flag would be neat.

**Comment by anderbubble** [comment]
Personally, I think that your rationale is sufficient to simply change the default behavior, and add a `--build` flag.
