### ISSUE TITLE
Where is a 'livesync' command?

### ISSUE THREAD

**Issue by frx-wintermute** [warewulf/warewulf#1405]
I am searching for a command to update running nodes, but I cannot find any in the documentation.

Please let me explain.
After importing a container and associating it to a number of compute nodes, it is my understanding that I can modify a container with
```console
# wwctl container exec CONTAINERNAME /bin/bash
(container)# WHATEVER...
(container)# UPGRADE...
(container)# exit
```

At that point Warewulf4 will automatically rebuid the VNFS image, if it detects that changes were applied by the WHATEVER... UPGRADE... commands. Is that correct?

This means that, when the compute nodes associated with the VNFS image boot, they will get the updated VNFS image.
Is that correct?

But what happens to the compute nodes that are already running?
Where is the command to live-update those nodes?

In the old Perceus provisioning system (which has been apparently dead-upstream for a long time, but I used to set up an old cluster) there was a 'livesync' command to live-update some or all the running nodes associated with a certain VNFS image, after modifying that VNFS image.
Where is an equivalent command in Warewulf4? Where is this command documented?

Thanks for reading so far and for any help you may provide.

```console
$ wwctl version
wwctl version:   4.5.5-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.5-1"
```

**Comment by anderbubble** [comment]
Warewulf v4 has no equivalent mechanism for synchornizing an updated image to a running system. Live updates come only from the node's "runtime" overlay, which is re-deployed periodically on each node.

The runtime overlay is documented at https://warewulf.org/docs/main/contents/overlays.html#runtime-overlay-or-generic-overlay

**Comment by frx-wintermute** [comment]
> Warewulf v4 has no equivalent mechanism for synchornizing an updated image to a running system. Live updates come only from the node's "runtime" overlay, which is re-deployed periodically on each node.
> 
> The runtime overlay is documented at https://warewulf.org/docs/main/contents/overlays.html#runtime-overlay-or-generic-overlay

Thanks for your very prompt answer.

But, wait, do you mean that I have to use overlays to deploy VNFS image upgrades (including security upgrades, performed daily)??? Or reboot compute nodes each time I upgrade a VNFS image (including security upgrades)???

I must be misunderstanding something: could you please elaborate a bit more on this topic?

**Comment by anderbubble** [comment]
Runtime overlays are for configuration; not for security updates.

Warewulf v4 expects you to reboot compute nodes to deploy an updated node image.

If you would like to discuss further, I suggest bringing your questions to the Warewulf Slack, rather than in issue comments.

Invite at https://warewulf.org/help/
