### ISSUE TITLE
Adding Netplan NIC support for Debian/Ubuntu

### ISSUE THREAD

**Issue by iankgt40** [warewulf/warewulf#1463]
### Summary

I would like to see support for default system tools in Debian/Ubuntu, such as the use of Netplan to configure network interfaces.

### Rationale

Per the Debian Netplan FAQ (https://wiki.debian.org/Netplan/FAQ):

Using Netplan gives a central location to describe simple-to-complex networking configurations that function from desktop to server and from cloud to IoT devices.

Specifically, for systems with systemd-networkd, this reliefs the user from having to configure up to three different files per device or configuration.

It provides a common and unified way to do network configuration across the distribution and brings a modern, hybrid network stack, consisting of systemd-networkd (for minimal, static server/cloud scenarios) and NetworkManager (for interactive, dynamic desktop/laptop scenarios, e.g. WiFi). All components of this Netplan + systemd-networkd/NetworkManager stack are well-tested, under active development and supported by a company. 

### Description

In testing, all that is needed is the creation of the rootfs/etc/netplan directory in the debian.interfaces and subsequent YAML file to be populated with known variables (I name it 01-netcfg.yaml.ww)

```
{{- $host := .BuildHost }}
{{- $time := .BuildTime }}
{{- $source := .BuildSource }}
{{range $devname, $netdev := .ThisNode.NetDevs -}}
{{- $filename := print $devname  }}
{{- file $filename }}
# This file is autogenerated by warewulf
# Host:   {{ $host }}
# Time:   {{ $time }}
# Source: {{ $source }}
{{ if $netdev.OnBoot.GetB -}}
{{ end -}}
network:
  version: 2
  renderer: networkd
  ethernets:
	{{$netdev.Device.Get}}:
  	addresses:
    	- {{$netdev.Ipaddr.Get}}/{{$netdev.Netmask.Get}}
#  	routes:
#    	- to: 10.10.10.0/{{$netdev.Netmask.Get}}
#      	via: {{$netdev.Gateway.Get}}
{{- end}}
```

### Additional information

The "routes" section is currently commented out, however, if Warewulf collects a defined network, the "10.10.10.0" network address could be replaced with something like "{{$netdev.Network.Get}}" and thus routing is defined in the Netplan config. 

Further, since the Netplan config file can handle multiple interfaces and virtual interfaces, it might be possible to iterate over multiple interfaces to populate the config file.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by anderbubble** [comment]
@iankgt40 thank you so much for getting this issue submitted.

Do you think this makes sense in a new "netplan" overlay, or grouped into the debian.interfaces overlay?
