### ISSUE TITLE
POSIX syntax for several scripts

### ISSUE THREAD

**Issue by iankgt40** [warewulf/warewulf#1464]
### Summary

While building and testing WW4 under Ubuntu 22.04 LTS and 24.04 LTS, it was discovered that several scripts broke due to Ubuntu/Debian use of /bin/dash instead of /bin/bash for /bin/sh. The scripts are:

overlays/wwinit/rootfs/warewulf/wwinit
overlays/wwinit/rootfs/init
scripts/build-ipxe.sh

### Rationale

Since Ubuntu and Debian both use dash, POSIX compliance is warranted. A simple workaround would be to force the use of bash, however, POSIX compliance is preferred in the event that bash is not available on the system, or some other environment requires it.

### Description

I have modified versions of the aforementioned scripts for POSIX compliance. Additionally, I have added commented out logic in the wwinit script to facilitate testing for the .sh suffix and exec bit on the scripts launched should that become needed.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by anderbubble** [comment]
@iankgt40 I wasn't paying enough attention: this is an issue, not a PR, and your updated scripts are not attached.

Can you submit a PR with the updated scripts?

**Comment by iankgt40** [comment]
Sure thing ... will do so shortly.

Ian

Ian Kaufman
Systems Integration Engineer
UC San Diego, Research IT Services
ikaufman AT ucsd DOT edu
________________________________

**Comment by iankgt40** [comment]
Hmmm, PR denied since I am not a "collaborator" ...


Ian Kaufman
Systems Integration Engineer
UC San Diego, Research IT Services
ikaufman AT ucsd DOT edu
________________________________

**Comment by anderbubble** [comment]
Anyone can submit a PR. You just can't push a branch into the Warewulf project: fork the repo into your account, push a branch there, and submit the PR from there.

**Comment by iankgt40** [comment]
Done!

Ian Kaufman
Systems Integration Engineer
UC San Diego, Research IT Services
ikaufman AT ucsd DOT edu
________________________________
