### ISSUE TITLE
wwctl node status gives an error

### ISSUE THREAD

**Issue by aaronhcarr** [warewulf/warewulf#1525]
### Steps to reproduce

wwctl node status

### Error message

[root@cghd-lxbiocomphpc1 ~]# wwctl node status
ERROR  : Could not decode JSON: invalid character '<' looking for beginning of value
ERROR: invalid character '<' looking for beginning of value

### Information on your system

[root@cghd-lxbiocomphpc1 ~]# wwctl version
wwctl version:   4.5.8-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.8-1"

[root@cghd-lxbiocomphpc1 ~]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
Thank you for the report, @aaronhcarr!

**Comment by aaronhcarr** [comment]
I will add that I've reinstalled Rocky 9.4, and installed warewulf-4.5.6-1.el9.x86_64.rpm, and the same thing happened with that version.

**Comment by anderbubble** [comment]
@aaronhcarr I have tried this on my v4.5.8 and main clusters and I don't see the same issue.

```
[janderson@wwctl1 ~]$ wwctl node status
NODENAME             STAGE                SENT                      LASTSEEN (s)
================================================================================
wwnode1              RUNTIME_OVERLAY      __RUNTIME__.img.gz        566016    
[janderson@wwctl1 ~]$ wwctl version
wwctl version:	 4.5.8-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.8-1"
```

```
[root@wwctl2 ~]# wwctl node status
NODENAME             STAGE                SENT                      LASTSEEN (s)
================================================================================
wwnode1              RUNTIME_OVERLAY      __RUNTIME__.img.gz        19        
[root@wwctl2 ~]# wwctl version
wwctl version:	 4.5.1test1+388.ge54ecfad.dirty-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.1test1+388.ge54ecfad.dirty-1"
```

From this, I expect that there's a parse issue dependent on your `nodes.conf` file. Can you share it?

**Comment by aaronhcarr** [comment]
Absolutely.

head node redacted.

[root@XXXXXXXXXXXXXXX ~]# cat /etc/warewulf/nodes.conf 
WW_INTERNAL: 45
nodeprofiles:
  compute:
    comment: Standard compute nodes
    container name: compute
  default:
    comment: This profile is automatically included for each node
    network devices:
      default:
        netmask: 255.255.252.0
        gateway: 172.16.0.1
nodes:
  c001:
    container name: compute
    profiles:
    - compute
    network devices:
      default:
        hwaddr: c4:5a:b1:a5:21:a1
        ipaddr: 172.16.0.101
        gateway: 172.16.0.1
      mpinet:
        type: ethernet
        device: eno12399np0
        ipaddr: 172.16.8.101
        netmask: 255.255.252.0
  c002:
    container name: compute
    profiles:
    - compute
    network devices:
      default:
        hwaddr: c4:5a:b1:bb:df:7f
        ipaddr: 172.16.0.102
        gateway: 172.16.0.1
      mpinet:
        type: ethernet
        device: eno12399np0
        ipaddr: 172.16.8.102
        netmask: 255.255.252.0
  c003:
    container name: compute
    profiles:
    - compute
    network devices:
      default:
        hwaddr: c4:5a:b1:c7:d9:83
        ipaddr: 172.16.0.103
        gateway: 172.16.0.1
      mpinet:
        type: ethernet
        device: eno12399np0
        ipaddr: 172.16.8.103
        netmask: 255.255.252.0
  c004:
    container name: compute
    profiles:
    - compute
    network devices:
      default:
        hwaddr: c4:5a:b1:c7:da:d1
        ipaddr: 172.16.0.104
        gateway: 172.16.0.1
      mpinet:
        type: ethernet
        device: eno12399np0
        ipaddr: 172.16.8.104
        netmask: 255.255.252.0
  c005:
    container name: compute
    profiles:
    - compute
    network devices:
      default:
        hwaddr: f0:d4:e2:fd:4e:9e
        ipaddr: 172.16.0.105
        gateway: 172.16.0.1
      mpinet:
        type: ethernet
        device: eno12399np0
        ipaddr: 172.16.8.105
        netmask: 255.255.252.0
  c006:
    container name: compute
    profiles:
    - compute
    network devices:
      default:
        hwaddr: c4:5a:b1:c9:87:d3
        ipaddr: 172.16.0.106
        gateway: 172.16.0.1
      mpinet:
        type: ethernet
        device: eno12399np0
        ipaddr: 172.16.8.106
        netmask: 255.255.252.0
  c007:
    container name: compute
    profiles:
    - compute
    network devices:
      default:
        hwaddr: c4:5a:b1:bf:40:63
        ipaddr: 172.16.0.107
        gateway: 172.16.0.1
      mpinet:
        type: ethernet
        device: eno12399np0
        ipaddr: 172.16.8.107
        netmask: 255.255.252.0
  c008:
    container name: compute
    profiles:
    - compute
    network devices:
      default:
        hwaddr: c4:5a:b1:bf:38:39
        ipaddr: 172.16.0.108
        gateway: 172.16.0.1
      mpinet:
        type: ethernet
        device: eno12399np0
        ipaddr: 172.16.8.108
        netmask: 255.255.252.0

**Comment by anderbubble** [comment]
ok, so it's not that.

I've looked at the code that's doing this: the `wwctl node status` command is fetching json from the Warewulf server. Apparently it's delivering something malformed.

Can you share the output of this command?

```
curl http://${ipaddr}:${warewulf.port}/status
```

Where `ipaddr` and `warewulf.port` are taken from the values in `/etc/warewulf/warewulf.conf`?

For example, here's mine right now:

```
$ curl http://192.168.3.10:9873/status
{
  "nodes": {
    "wwnode1": {
      "node name": "wwnode1",
      "stage": "",
      "sent": "",
      "ipaddr": "",
      "last seen": 0
    }
  }
}
```

**Comment by aaronhcarr** [comment]
This doesn't look at all like the output you have.

What could cause this?

[root@cghd-lxbiocomphpc1 ~]# curl http://172.16.0.1:9873/status
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>


<head>
  <meta http-equiv="X-UA-Compatible" content="IE=7" />
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <title>McAfee Web Gateway - Notification</title>
  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
  <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/utsw/stylesheet.css" />
</head>



<body onload="swOnLoad();">
  <table class='bodyTable'>
    <tr>
      <td class='bodyData' background='/mwg-internal/de5fs23hu73ds/files/utsw/img/bg_body.gif'>


<table class='logoTable'>
  <tr>
    <td class='logoData'>
        <img src='/mwg-internal/de5fs23hu73ds/files/utsw/img/utswLogo.jpg'></a>
    </td>
  </tr>
</table>





<table class='titleTable' background=''>
  <tr>
    <td class='titleData'>
      Blocked by URL Filter Database
    </td>
  </tr>
</table>


<table class="contentTable2">
  <tr>
    <td class="contentData2">
     Your requested URL has been blocked by the URL Filter database module of McAfee Web Gateway. The URL is listed in categories that are not allowed by university policy at this time.
    </td>
  </tr>
</table>

<hr>

<table class="infoTable">
  <tr>
    <td class="infoData">
      <b>URL: </b><script type="text/javascript">break_line("http://172.16.0.1:9873/status");</script> (172.16.0.1)<br />
      <b>Client_IP: </b> 129.112.48.34<br />
      <b>User: </b> <br />
      <b>Policy: </b> default <span class="nodisplay-">(-)</span><br />
      <b>Rule: </b> Block Uncategorized Web Sites <br />
        <script type="text/javascript">
          writeToDocument("<b>URL Categories: </b>" + "" );
        </script><br />
      <b>Reputation: </b>Unverified (15) <br />
      <b>User Agent: </b>curl/7.76.1<br />
    </td></td></tr>
</table>


<table class="optionsTable">
  <tr>
   <td class="optionsData">
      <br />
    </td>
  </tr>
  <tr>
    <td class="optionsData">
     <center>If you believe this site has been blocked in error -<br /><br />

      <form><input value="Click here to email a site review request to the IR Service Desk" onclick="location.href='mailto:ServiceDesk@UTSouthwestern.edu?Subject=Site Review Request&Body=Site Review Request%0D%0ABlock Reason: Block Uncategorized Web Sites (CHG0080139 CTASK0141092 CTASK0142037 CTASK0142040)%0D%0AURL: http://172.16.0.1:9873/status%0D%0AClient_IP: 129.112.48.34%0D%0AUser: %0D%0APolicy: default (-)%0D%0ACategories: %0D%0AReputation: Unverified (15)%0D%0AVirus Name: -%0D%0AMedia Type: %0D%0AUser Agent: %27curl/7.76.1%27%0D%0ADate: 2024-11-06 23:15:24%0D%0A%0D%0AComments:%0D%0A'"
        type="button">
      </form>

     </center>
    </td>
  </tr>
</table>


<table class='policyTable2'>
  <tr>
    <td class='policyHeading2'>
      <hr>
      Internet Usage Policy
    </td>
  </tr>
  <tr>
    <td class='policyData2'>
You have attempted to access a website that is restricted because it may violate
 the
 <a href=https://utsouthwestern.policytech.com/docview/?docid=69&anonymous=true>Acceptable Use of Information Resources (ISR-104)
</a>. Internet activity is monitored and
 suspected violations are investigated for appropriate disciplinary action up to,
 and including termination. You may have received this message because you made a
 keystroke error while attempting to access a legitimate website. Please check your
 web address.
    </td>
  </tr>
</table>




<table class='footTable'>
  <tr>
   <td class='helpDeskData'>
      For assistance, please contact the IR Service Desk at 214-648-7600.
    </td>
  </tr>
  <tr>
    <td class='footData'>
      generated <span id="time">2024-11-06 23:15:24</span> by McAfee Web Gateway [129.112.115.40]
      <br />
      curl/7.76.1
      <br />
     Block Uncategorized Web Sites
    </td>
  </tr>
</table>


      </td>
    </tr>
  </table>
</body>

**Comment by aaronhcarr** [comment]
Could this be caused by the use of a proxy server?

Customer is using a proxy.

I've just added no_proxy=172.16.0.1

But that didn't change the output of wwctl node status

**Comment by anderbubble** [comment]
Yep, that'd be it.

As for why setting `no_proxy` didn't work, maybe you only set a shell variable rather than an environment variable?

In any case: not a Warewulf bug, so closing this issue.

**Comment by aaronhcarr** [comment]
Thank you for the information.

Going to leave this with them.

We know how to get around it.
