### ISSUE TITLE
"wwnodescan" command never ends

### ISSUE THREAD

**Issue by iquasere** [warewulf/warewulf#1585]
### Steps to reproduce

So, I setup five VMs with VirtualBox, one as a master node, where I installed warewulf and its friends, following the [OpenHPC tutorial](https://github.com/openhpc/ohpc/releases/download/v3.2.GA/Install_guide-Rocky9-Warewulf-SLURM-3.2-aarch64.pdf). 

I got stuck when trying to run the command:
`wwnodescan --netdev=${eth_provision} --ipaddr=${c_ip[0]} --netmask=${internal_netmask} \
--vnfs=rocky9.3 --bootstrap=`uname -r` --listen=${sms_eth_internal} ${c_name[0]}-${c_name[3]}`
 
The command never ends, and outputs nothing!

### Error message

The command itself gives no error. But when booting the compute node VM that would be assigned to warewulf's network, I get this error:

![{9F28F320-CBFC-4C93-9F17-462D1F621BF0}](https://github.com/user-attachments/assets/983611fe-f23a-4cc1-8577-e7909b27507b)

Which is weird, because running `ls /var/lib/tftpboot/warewulf/ipxe/bin-i386-pcbios/undionly.kpxe` I can see the file is there. So this seems like a TFTP problem! But running `journalctl -u tftp` gives me:
```
Dec 06 06:10:04 vbox systemd[1]: Started Tftp Server.
Dec 06 06:10:04 vbox in.tftpd[3851]: Client ::ffff:10.0.8.1 finished warewulf/ipxe/bin-i386-pcbios/undionly.kpxe
Dec 06 06:25:10 vbox systemd[1]: tftp.service: Deactivated successfully.
```
Which seems fine? Honestly, I'm too inexperienced to know what is going on here, and have exhausted my capabilities. Which is a shame, because warewulf seems like a really cool tool, and easy to use. Just not by me.

### Information on your system

Following OpenHPC's instructions, I ended up not having the `wwctl` executable. In fact, running `find / -name "wwctl"` doesn't find it. But I did install the `ohpc-warewulf` package, so I am at a loss there eiter. Not the point of this issue, tho.

`cat /etc/os-release`
```
NAME="Rocky Linux"
VERSION="9.5 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.5 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
VENDOR_NAME="RESF"
VENDOR_URL="https://resf.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.5"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.5"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
wwnodescan is a Warewulf 3 command. This GitHub is for Warewulf 4. If you want to be deploying Warewulf 4, use the OpenHPC guide at https://github.com/openhpc/ohpc/releases/download/v3.2.GA/Install_guide-Rocky9-Warewulf4-SLURM-3.2-x86_64.pdf. (Note that they currently only have a guide for Slurm on x86_64.)

**Comment by anderbubble** [comment]
If you _do_ want to run Warewulf 3, you can ask for help on the OpenHPC Slack or in the #warewulf3 channel in the Warewulf Slack.
