### ISSUE TITLE
sysconfdir path specified in --warewulfconf file doesn't affect lookup of nodes.conf

### ISSUE THREAD

**Issue by mslacken** [warewulf/warewulf#1596]
### Steps to reproduce

* install a ww4 instance/lcuster with one of the rpm packages
* compile `wwctl` on another machine without any other setting
* copy `wwctl` to ww4/cluster
* run `wwctl  --warewulfconf=/etc/warewulf/warewulf.conf node list`

### Error message

```
./wwctl --warewulfconf=/etc/warewulf/warewulf.conf nodes list
ERROR: open /usr/local/etc/warewulf/nodes.conf: no such file or directory
```

### Information on your system

PRETTY_NAME="openSUSE Leap 15.6"
wwctl version:	 4.6.0-1

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by mslacken** [comment]
This is fixed by #1569 and *NOT* #1595

**Comment by anderbubble** [comment]
It is not clear to me that `--warewulfconf` should definitely affect the lookup path for `nodes.conf`.

I haven't noticed yet how (nor confirmed that) #1569 actually does this; but now that I see what you're after I'll check that out explicitly.

**Comment by anderbubble** [comment]
#1569 doesn't appear to change this behavior.

```
$ ls /etc/warewulf{,/subdir}
/etc/warewulf:
examples  grub  ipxe  keys  subdir

/etc/warewulf/subdir:
nodes.conf  warewulf.conf

$ sudo wwctl --warewulfconf /etc/warewulf/subdir/warewulf.conf node list -a
ERROR: open /etc/warewulf/nodes.conf: no such file or directory
```

I think, to do what you want, we need to add a `--nodesconf` argument alongside `--warewulfconf`.

**Comment by mslacken** [comment]
The values of `sysconfdir` is affected by `warewulf.conf` . So `warewulf.conf` is the only single source of truth.

**Comment by mslacken** [comment]
> #1569 doesn't appear to change this behavior.
> 
> ```
> $ ls /etc/warewulf{,/subdir}
> /etc/warewulf:
> examples  grub  ipxe  keys  subdir
> 
> /etc/warewulf/subdir:
> nodes.conf  warewulf.conf
> 
> $ sudo wwctl --warewulfconf /etc/warewulf/subdir/warewulf.conf node list -a
> ERROR: open /etc/warewulf/nodes.conf: no such file or directory
> ```
> 
> I think, to do what you want, we need to add a `--nodesconf` argument alongside `--warewulfconf`.

Is the `Sysconfdir` value set in your `warewulf.conf`?

**Comment by anderbubble** [comment]
> The values of sysconfdir is affected by `warewulf.conf`.

I see. Now I understand, at least a little bit better.
