### ISSUE TITLE
`wwctl overlay delete` ignores third argument

### ISSUE THREAD

**Issue by robgjansen** [warewulf/warewulf#178]
I get an error when trying to delete a file from an overlay:

```
$ sudo wwctl overlay delete runtime default /etc/security/limits.conf
ERROR: refusing to delete the default overlay
```

I'm trying to delete the file, not the overlay itself, so the error message indicates that `wwctl` is ignoring the third argument (the filename).

```
$ wwctl overlay delete
ERROR: accepts between 2 and 3 arg(s), received 0
```

**Comment by gmkurtzer** [comment]
Hi @robgjansen, great catch! If possible, can you please test the above PR?
