### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jcsiadal** [warewulf/warewulf#254]
This one is obvious. Since the major overlay and makefile rework, the current documentation is obsolete. https://warewulf.org/docs/

We should consider an accessible documentation snapshot that is accurate to each major release, along with a doc area that tracks the main branch.

**Comment by anderbubble** [comment]
There's clearly more work to be done on docs; but I'm closing this overall ticket for now, since we now have a separate main and v4.5.x docs section.
