### ISSUE TITLE
add `--output [text|csv|json|yaml]` option for `wwctl` commands that produce output.

### ISSUE THREAD

**Issue by griznog** [warewulf/warewulf#447]
It'd be nice when writing tools/scripts that use `wwctl` output if there were some script-friendly formats available that don't require pulling apart the human readable default output. I'm hoping that at least JSON will be trivial to implement once things move to the API model, which will need to pass things around as JSON (or YAML?) by design.

**Comment by jmechalas** [comment]
This is sorely needed.

**Comment by anderbubble** [comment]
I discovered this had 4.4 in the title, so I've added it to the milestone for now.

**Comment by JasonYangShadow** [comment]
I think I can take care of this issue
