### ISSUE TITLE
`wwctl node set` wants to modify nodes even though no other arguments

### ISSUE THREAD

**Issue by griznog** [warewulf/warewulf#502]
Observed behavior:

```
[I am root!@frankie:(bare)::~]# wwctl node set 

*** WARNING: This command will modify all nodes! ***

? Are you sure you want to modify 55 nodes(s)? [y/N] █
```

Expected behavior:

An error or usage message.

**Comment by mslacken** [comment]
If its on the `development` branch we will have to postpone this until the merge of #495 as the `wwctl node set` interface changed here/

**Comment by griznog** [comment]
This is on `main`, but it's not really a serious bug (unless something bad happens if I choose Yes, which I haven't tested.) It was just not what I expected the command to do with no arguments.
