### ISSUE TITLE
do not daemonize or write pid files

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#508]
I've been reading [the twelve-factor app docs](https://12factor.net/concurrency) and specifically this part:

> Twelve-factor app processes [should never daemonize](http://dustin.github.com/2010/02/28/running-processes.html) or write PID files. Instead, rely on the operating system’s process manager (such as [systemd](https://www.freedesktop.org/wiki/Software/systemd/), a distributed process manager on a cloud platform, or a tool like [Foreman](http://blog.daviddollar.org/2011/05/06/introducing-foreman.html) in development) to manage [output streams](https://12factor.net/logs), respond to crashed processes, and handle user-initiated restarts and shutdowns.

As such, I propose the following changes:

- remove `wwctl server [restart|stop|status]`
- remove `wwctl server start --foreground` (it should always be foreground)
- stop writing pidfiles
- update warewulfd.service to use new foreground semantics (and maybe rename it to warewulf-server, since there isn't actually a warewulfd process)

But I recognize this is a broad and high-impact suggestion: hence the "rfc" tag for this issue. I'd love to hear thoughts on the viability of a proposal like this.

**Comment by griznog** [comment]
+1 for this change. Not many things I hate more than `systemd` but it is inevitable at this point so it should be the default target for how to run the warewulf server daemon.

**Comment by anderbubble** [comment]
Agreed in TSC discussion.
