### ISSUE TITLE
package and document update_configuration

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#517]
I recently discovered the `update_configuration` utility in the Warewulf source. I think this would be generally useful, particularly as more people start using Warewulf 4 when it gets published in OHPC. With that, I suggest that the RPM spec file be updated to include the update_configuration command.

It could be distributed as-is in a non-PATH location (e.g., something like a libexec); but if we put it in `*bin/` I suggest it could be renamed to something like `wwcfg`.

**Comment by mslacken** [comment]
As long as the code is capable of reading the old configs and recreate a new one on the fly (how its done at the moment), packaging this tool might create some confusion at the moment.
The situation will change, if the WW_INTERNAL is really used.
