### ISSUE TITLE
Support for large boot images in Legacy BIOS mode

### ISSUE THREAD

**Issue by IngoMeyer441** [warewulf/warewulf#582]
This is related to issue #497 and PR #500.

We still have machines in production use which have no or bad support for UEFI so we stick with BIOS boot at the moment. PXE boot roms are typically bound to the 3GB barrier in BIOS mode which makes it hard to load large boot disks. Is there a recommended way to handle this limitation?
One possible solution could be to load a small image with Warewulf, boot it and get a second larger image which is handled by the Linux kernel and can make use of the whole RAM. But of course it would be much more elegant to handle this only with Warewulf itself.

**Comment by griznog** [comment]
Your proposed solution is what previous WW versions have done and what some other provisioners do and is, as far as I know, the only way to skirt the Legacy BIOS 32 bit addressing issue. To unpack/load anything larger than will fit in ~3 GB means doing it *after* the kernel is started and not in iPXE as an initrd. 

Building that small image is the difficult step, but you might be able to cheat a bit by just having a minimal container that is an exact subset of your actual container and add to wwinit a script to bring up a network device, pull the larger container image and overwrite the minimal `/` just before the `pivot_root` and hand-off to the container init.

Yet another alternative is to add a `systemd` service to your minimal image that does a `dnf install ...` after the network comes up and just install all the packages you need to make it match your large image. We do this to add libreoffice and a bunch of other stuff to nodes that will become remote desktops. 

I've found that getting the latest BIOS helps with UEFI support, so if you haven't already tried updating the BIOS, that might get you a working UEFI.

**Comment by IngoMeyer441** [comment]
Thanks for the quick response. I think I will try the small/large image concept. This is probably also interesting as a native feature in Warewulf, isn't it? Or was this feature removed because it is not necessary for UEFI machines?

**Comment by griznog** [comment]
I can't speak to the reasons behind the original design choice for WW4, but in the past when using WW <=3 and having differing kernel versions between VNFS and the initial shim kernel/image I've had a few bits of "weirdness" that I couldn't reproduce on systems that didn't do a `kexec()` but also couldn't trace precisely to the `kexec()` as the issue. IMO, it's cleaner if you can avoid doing a `kexec()` during provisioning. Time may have resolved my concerns as well, `kexec()` may be more stable/reliable than it was years ago when I saw this behavior. 

UEFI (when it's recent and working well) is a lot nicer to manage than legacy BIOS, so *if* it actually worked everywhere then that'd be a win. Other/newer architectures use UEFI and lack Legacy BIOS so it's really the future, although when the future actually gets here may not be all that soon, seems like fixes for UEFI are in pretty much every BIOS upgrade I do :)

**Comment by anderbubble** [comment]
It should be possible to boot large images with legacy bios mode now that we can boot via dracut.
