### ISSUE TITLE
Short hostname not appearing in /etc/hosts unless the "default" network is configured

### ISSUE THREAD

**Issue by jtoddowen** [warewulf/warewulf#632]
Using the `default` network name creates an `/etc/hosts` file entry similar to the following: `192.168.155.101 c01-default c01-eno1np0 c01`.

However, when a `wwctl node set --netdel=default c01` is issued and an alternative network name is assigned in a profile, such as `wwctl profile set --netname eth1 --netdev eno1np0`, the `/etc/hosts` entry looks like `192.168.155.101 c01-eth1 c01-eno1np0` **_without_** the short node name `c01` appended.

**Comment by NateCrawford** [comment]
For now, you can manually set one network to be the primary in the node config (see #629 and #630 for some related stuff). The short host name should be added to that line in /etc/hosts. Example:

wwctl node set --netname eth1 --primary true c01

**Comment by mslacken** [comment]
Right in 4.4.0 you should get the short hostname if the primary flag is set. If now this would be undetermined.
