### ISSUE TITLE
Boot nodes with minimal initrd instead of full container

### ISSUE THREAD

**Issue by griznog** [warewulf/warewulf#664]
Booting nodes with large images/containers remains problematic due to Legacy BIOS vs. UEFI vs. Bad Hardware(tm) [1]. In addition on some hardware UEFI/iPXE performs very poorly getting a large image into memory and passing control to the kernel [2]. This RFE is to return to the WW3 and earlier approach of booting with a small bootstrap `initrd` which then pulls the full container/image. However, this proposal differs in that the bootstrap `initrd` will be built from each container, specifically for each container.

# Design points

1. The kernel used will be the kernel assigned to the node, no need for a `kexec` call to switch kernels after the initial bootstrap.
2. The `initrd` used will be built from the container itself using `dracut` so that it matches the deployed image.
3. The `initrd` built by `dracut` will include the network or networkmanager modules to provide networking support in the `initrd`
4. The current `wwinit` network setup can be replaced (in all or part) by passing network configuration on the kernel command line, the `dracut` network/networkmanager modules then pass that config to the nodes NetworkManager automatically. 
5. `busybox`, `wwinit` and other modifications or customization to the `initrd` are passed in as overlays over the `dracut` `initrd` image.
6. Because a fully featured `tar`, `rsync` or other similar method can be used to fetch the full container image, SELinux labels can be included with the upstream image and full extended attribute and ACL support is available for deployed node images without the need to relabel at boot time.  

I've tested this, very crudely, to the point of booting a node from a `dracut` `initrd` with an arbitrary overlay applied to it to get a shell on the node. But, so far, so good and there don't seem to be any major obstacles to using this approach, at least on RHEL-8 era and later derivatives. There may be necessary bits missing from `dracut` or `systemd` on earlier OS releases. 

# Footnotes 
[1] I have 2 blade chassis, 40 blades total, which hang at random points while downloading a large container image. Repeated power cycling will eventually get them booted, but a small bootstrap `initrd` approach would solve the problem elegantly. We also have a few older nodes that even with UEFI will not boot a container/image larger than about ~ 8GB. 

[2] Wall clock watching on some nodes shows it can take UEFI/iPXE 2 to 3 minutes to unpack the large `initrd` before pulling the overlays. Additionally, iPXE has some cards negotiate fast ethernet speeds, requiring the large boot image to be downloaded at 100Mbps. This adds significant time to the boot process.

**Comment by anderbubble** [comment]
I'm closing this since we've basically started doing this with the nascent dracut support; but let me know if I've missed anything.
