### ISSUE TITLE
the warewulf server should be able to omit send/recv log messages

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#725]
### Version of Warewulf

4.4

### Expected behavior

It should be possible, either through a setting in warewulf.conf or a command-line argument to `wwctl server start`, to decrease the verbosity of the warewulf log such that send and recv messages are not written.

### Actual behavior

send/recv messages are always written, and verbosity can only be increased.

**Comment by mslacken** [comment]
I think you can solve this by passing the verbosity level to the child process like here 
https://github.com/hpcng/warewulf/blob/dd3b34a2c64d463d27a1010088c5cc10217f2950/internal/app/wwctl/container/exec/main.go#L39
We should also consider to make the verbosity level to adapted in the warewulf.conf file, but I would think that would need the merge of #721 as there also the read process of warwulf.conf was changed.

**Comment by mslacken** [comment]
You seem to have used the wrong binary. The actual development one uses this flag
```
./wwctl --loglevel=5 node list
DEBUG  : Set log level to: 5, DEBUG
```
btw. the flag is numeric and its hidden as for normal users there is allready `d` and `-v`. I just didn't want to have a logic which converts the log level again back to this flags.

**Comment by anderbubble** [comment]
It looks like warewulfd also reads verbosity from `WAREWULFD_LOGLEVEL`; so if we just add an environment file to the systemd unit that'd make it pretty easy to set.
