### ISSUE TITLE
iPXE imgextract/initrd with secure: true in warewulf.conf causes node boot failure

### ISSUE THREAD

**Issue by rthomson** [warewulf/warewulf#806]
### Version of Warewulf

4.4.0-1.git_afcdb21

### Expected behavior

When setting `secure: true` in `warewulf.conf`, iPXE `imgextract` or `initrd` commands should download runtime overlay from a secure client port

OR

iPXE should skip download of runtime overlay (when using `secure: true`) if it cannot use a secure client port for download and let `wwclient` perform the "first" runtime overlay sync instead.

### Actual behavior

iPXE returns a "permission denied" error and fails to boot when trying to download the runtime overlay on boot with `secure: true` set in `warewulf.conf`

If I comment out `imgextract` / `initrd` for the runtime overlay in `default.ipxe` (when using `secure: true` in `warewulf.conf`), nodes boot successfully and start `wwclient` after `init`, which is then able to download and apply the runtime overlay using a secure client port.

### Steps to reproduce this behavior

1. Set `secure: true` in `warewulf.conf`
2. Restart `warewulfd` service
3. Rebuild (runtime) overlay(s)
4. Reboot node(s)
5. Node fails to boot due to iPXE "permission denied" on the runtime overlay.

### What OS/distro are you running

Rocky Linux 9.1

### How did you install Warewulf

Source build.

**Comment by anderbubble** [comment]
Thanks for the report. I'm surprised, because I checked this and was sure I saw it working just recently, but I'll look into it.

**Comment by rthomson** [comment]
Thanks for looking into it! I'm happy to provide additional information, testing or fixes where helpful.

Here's a screenshot of the error in my test environment (VMware):

![image](https://user-images.githubusercontent.com/1192904/236281873-0ff83462-aa5b-4729-b4fa-33af5701d396.png)

and I believe this is the line in `default.ipxe` that is causing the error with `secure: true`:

https://github.com/hpcng/warewulf/blob/ab52e389f6fce2681b456d24dc2b6a5d9feb46eb/etc/ipxe/default.ipxe#L82

Commenting the above line results in a successful boot where `wwclient` applies the runtime overlay instead of iPXE.

**Comment by jeburks2** [comment]
Seeing this same issue. Also on version 4.0-1.git_afcdb21. In the Warewulf logs shows client is attempting to use non-privilege port :61176. Would expect client to use a privileged port. Commenting out  Line 82 of warewulf/etc/ipxe/default.ipxe allows the client to boot in secure mode

**Comment by scranfor** [comment]
I believe I'm also seeing this issue on version 4.4.1-1.git_d6f6fed, compiled from the release tarball. 

I'm in the beginning stages of setting up a cluster with Warewulf and having this fixed will make my security folks happy.

**Comment by rthomson** [comment]
I can confirm the behaviour described here remains the same with warewulf 4.5.0 and a custom compiled iPXE 1.21.1 on Rocky Linux 9 with UEFI boot on modern Lenovo hardware.

The workaround of disabling the runtime overlay download during the iPXE stage allows the node to boot with `secure: true` set in `warewulf.conf` but unfortunately various services configured with runtime overlays then don't start as expected on node boot. I suspect this is because `wwclient` doesn't pull down the runtime overlay before kicking off the init process.

As best I can tell, there is no existing functionality to specify source port for HTTP(S) requests with iPXE so I see two possible solutions:

1. Work with iPXE project to develop support for specifying HTTP(S) source port for iPXE.
2. Modify the warewulf node init process to start `wwclient` to download the runtime overlays _before_ systemd init.

For possible solution 2, I see that the `wwinit` overlay avoids manually starting `wwclient` if  systemd is present: https://github.com/warewulf/warewulf/blob/3d128039781819f73fe79c8bf39f9eb480d169bc/overlays/wwinit/rootfs/warewulf/init.d/80-wwclient.ww#L9

Perhaps a fix here would be to run `wwclient` once during init even if systemd is expected to start the `wwclient` service later during boot? For this scenario perhaps `wwclient` needs a `--once` argument or similar where it runs just once to download the runtime overlay and then exits? I will test single execution of `wwclient` from init without `nohup` to see if I can maybe get this working with a bit of hack and report back.

I have not verified if this issue exists with the experimental grub boot but I would suspect it does unless we're explicitly telling grub to use privileged source ports for HTTP.

**Comment by rthomson** [comment]
Dang, seems like the network isn't available at the time init executes `80-wwclient` (which I suppose makes sense since systemd brings up the network by starting NetworkManager):

> 2024/04/11 16:31:56 Get "http://192.168.xxx.251:9873/provision/6c:fe:54:57:a2:84?assetkey=<redact>&uuid=<redacted>&stage=runtime&compress=gz": dial tcp :987->192.168.xxx.251:9873: connect: network is unreachable

**Comment by epruesse** [comment]
This could be patched, in theory:

https://github.com/ipxe/ipxe/blob/b66e27d9b29a172a097c737ab4d378d60fe01b05/src/net/tcp/httpconn.c#L296-L302

Would have to become

```c
        struct sockaddr_tcpip   local; //new
        //...
	/* Open socket */
	memset ( &server, 0, sizeof ( server ) );
	server.st_port = htons ( port );
        memset ( &local, 0, sizeof ( local ) ); //new
        local.st_flags = TCPIP_BIND_PRIVILEGED; //new

	if ( ( rc = xfer_open_named_socket ( &conn->socket, SOCK_STREAM,
					     ( struct sockaddr * ) &server,
					     uri->host, (struct sockaddr*) &local) ) != 0 ) //changed
		goto err_open;
```

That would make this patched  version of ipxe use privileged ports for http. 

Now what I don't get is how this ever could have worked. The lines in iPXE that do the search for free ports have been randomizing ports and selecting non-privileged ones for over a decade...

**Comment by anderbubble** [comment]
I suspect that the iPXE template used to be more lenient about not being able to download the runtime overlay, and just ignored it until later.

Fixing that (letting iPXE continue trying to boot even if it can't get the runtime overlay) is probably the best available fix right now. Though I do want to revisit Warewulf security overall.

**Comment by upsj** [comment]
I just wanted to leave this discussion here for some context: The iPXE maintainers themselves don't recommend using privileged source ports for security purposes https://github.com/ipxe/ipxe/discussions/1282
