### ISSUE TITLE
wwctl power should be wwctl node power

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#820]
Most ipmi functionality (sensors, console) are nested within node; but power is on its own. It should be nested under node as well.

wwctl power should be retained as an alias for now.

**Comment by henkela** [comment]
Hi, 
I'd like to suggest to change the default behaviour of wwctl node power, too. Currently, if wwctl power <command> is called it is executed for all nodes. I'd suggest either a safety net like asking for confirmation or change the default that if no node-string(s) are entered the command fails and asks for node-string(s). 
Best,
Andreas

**Comment by epruesse** [comment]
duplicate of #560

**Comment by anderbubble** [comment]
Heh, thanks @epruesse

**Comment by henkela** [comment]
Hi,
That wasn’t the point of my issue. I asked for changing the default behaviour of the subcommand power not if it is a sub command or in which category it resides.
We had the issue that inexperienced users typed wwctl power something expecting to see some help on the syntax but instead the “something” was triggered for all nodes (which was a reset on nodes running user processes). Therefore I asked for a failing wwctl power command if no node name or node list is given.

Am 07.10.2024 um 19:00 schrieb Jonathon Anderson ***@***.***>:

﻿

Heh, thanks @epruesse<https://github.com/epruesse>

**Comment by epruesse** [comment]
I think that must have been fixed. I don't recall running into Solaris killall like behavior.

**Comment by epruesse** [comment]
Not going to try is now though...

**Comment by anderbubble** [comment]
@henkela I agree with the behavior preference you suggest; but your comment was not the origin of this issue.

You can either repeat your comment at #560 or (probably better) open a distinct issue for it.
