### ISSUE TITLE
wwinit scripts have mixed / conflicting shebang lines with how they are actually called

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#821]
The wwinit scripts at https://github.com/hpcng/warewulf/tree/development/overlays/wwinit/warewulf/init.d have shebang lines, but they are not actually executed: they are run explicitly by `sh`. This is further confused by some of them having bash shebangs.

We should update these to not have a shebang, update them to all be /bin/sh, or update wwinit to run the scripts as executables.

**Comment by mslacken** [comment]
I would recommend to use '#/bin/sh' to make it clearly visible that these files are scripts, even as these scripts are explicitly run by sh

**Comment by anderbubble** [comment]
@mslacken any reason _not_ to just run the scripts as executables? That would let downstream admins write scripts in other languages than pure POSIX sh. (e.g., they could write them in Bash, Python, etc.)

**Comment by mslacken** [comment]
The problem here is that we call later systemd which must have pid 1. When allowing all kind of languages this could not guaranteed any more.

**Comment by anderbubble** [comment]
Isn't systemd being pid 1 guaranteed by virtue of Warewulf's init/wwinit having pid 1 and then being replaced by exec?

**Comment by mslacken** [comment]
Right, so just change it.
