### ISSUE TITLE
container modification lock during shell/exec

### ISSUE THREAD

**Issue by NateCrawford** [warewulf/warewulf#830]
### Version of Warewulf

What version of Warewulf are you using? 
```
wwctl version:	 4.4.0-1.git_afcdb21
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0-1.git_afcdb21"
```

### Expected behavior

"wwctl container shell containername" should block if containername already in use

### Actual behavior

Containers can be open multiple times simultaneously

### What OS/distro are you running

```
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```

### How did you install Warewulf

RPMs built from source

### Additional Notes:
I accidentally had the same container open in two different shells, and may have made conflicting minor edits. This could happen non-accidentally with multiple administrators. Can "wwctl container shell" set and check for a per-container lock file at start? Lock removal should happen automatically on exit, but there should be an option to override it.

**Comment by mslacken** [comment]
`wwctl container shell` is just calls `wwctl container exec $CONTAINER $SHELL` so its enough to have a lock file for `wwctl container exec`
