### ISSUE TITLE
separate project-provided and user-defined overlays

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#831]
Warewulf should read overlays from `/etc/warewulf/overlays/`, separate from where system overlays are read from. (Right now that's `/var/lib/warewulf/overlays/` on EL.)

Benefits:

* User overlays are kept separate from warewulf default overlays wwinit and generic
* Users are encouraged to create new overlays rather than modify existing overlays
* Lets user overlays be kept in the same git repo with all of /etc/warewulf

**Comment by anderbubble** [comment]
@griznog what'd you think of this?

**Comment by NateCrawford** [comment]
Is it possible to add a custom local host overlay? Right now, I have moved host/etc/exports.ww to host/etc/exports.d/ww.exports.ww so WW-managed exports can be a subset. With a local "host-override" overlay, would having {{ abort }} in etc/exports.ww and the custom one in etc/exports.d/ do the same thing?

**Comment by griznog** [comment]
You can add as many overlays as you want:

```
# wwctl overlay create --help

This command creates a new empty overlay with the given OVERLAY_NAME.

Usage:
  wwctl overlay create [OPTIONS] OVERLAY_NAME

Options:
  -h, --help   help for create

Global Options:
  -d, --debug     Run with debugging messages enabled.
  -v, --verbose   Run with increased verbosity.
 
```

If you want to start from an existing overlay you can just make a copy of one in the overlay directory with `cp -a` and then make any changes you want.

**Comment by griznog** [comment]
Overlays aren't special, except in how a 'system' overlay is treated differently than a 'runtime' overlay post-boot on the node.

**Comment by NateCrawford** [comment]
I'm asking about local modifications to the host overlay. I can see where to apply multiple system and runtime overlays to nodes, but not how to add extra host overlays to the head node.

**Comment by griznog** [comment]
Sorry, I'm being dense and read "host" as "system". No, I'm not aware of how you add additional host overlays, which seems like it should be possible. I use multiple overlays on my hosts buy applying them manually, but that's very custom and Fraught With Peril(tm) and I haven't yet convinced myself it is a good idea.

**Comment by anderbubble** [comment]
@NateCrawford I think that'd be a reasonable feature request, if you wouldn't mind submitting it as a separate issue from this one.

**Comment by NateCrawford** [comment]
Sure. I'll reference this issue for background.

**Comment by anderbubble** [comment]
Discussed in the 7 August 2024 TSC meeting.

- Christian: maybe forego configuration for now; just do /usr/share/warewulf/overlays and /etc/warewulf/overlays.
- Jeremy: recommends against /etc/warewulf, maybe keep /var/lib/warewulf
- Writes (and chmod, chown) should _always_ go to the write side (e.g., /var/lib/warewulf, not /usr/share/warewulf)
- During an edit, copy the entire overlay to the write location (e.g., from /usr/share/warewulf/overlays/ifcfg to /var/lib/warewulf/overlays/ifcfg), and only ever build an overlay from a single location.
