### ISSUE TITLE
Included overlays should be installed as examples

### ISSUE THREAD

**Issue by griznog** [warewulf/warewulf#875]
It's currently cumbersome to modify things in `wwinit` and `generic` overlays as that can be impacted by future upgrades. Overriding things in them in admin created overlays requires removing the thing being overriden from them or naming the admin created overlay such that it sorts correctly to be applied after `wwinit` / `generic`.

Proposing two ideas to address this:

1. Rename the included overlays with a prefix to control the order they sort in, e.g. instead of `wwinit` call it `00-wwinit` so that any site created overlays will always override it by default when the same file is included in multiple overlays.
2. Install the overlays included with warewulf as examples, e.g. `00-wwinit.example` and then have the user clone them at setup time for actual use by the default profile, maybe clone as part of the rpm/dev install/upgrade if the non-example version doesn't already exist.

Follwoed by some new `wwctl` commands to help working with overlays:

1. Add a `wwctl overlay clone overlay new-overlay` command which clones an existing overlay. 
2. (Super-optional) Add a `wwctl overlay rename overlay new-overlay` command which renames an overlay and also updates any nodes configs that were using the old overlay to point to the new-overlay name. 

Note this assumes the overlay sorting is a feature that will continue to work and not a side effect that may change randomly in the future.  Yet another RFE/discussion about that is here: https://github.com/hpcng/warewulf/issues/507#issuecomment-1205209512

**Comment by anderbubble** [comment]
I think we probably want to replace this with https://github.com/warewulf/warewulf/issues/831, but I'll add it to a discussion agenda.
