### ISSUE TITLE
tftp root directory

### ISSUE THREAD

**Issue by mslacken** [warewulf/warewulf#877]
### warewulf devel

There are two variables which refer to the tftp root directory which are
* https://github.com/hpcng/warewulf/blob/546007423cff17d5bbdd966f7b392b6b0b20ab45/internal/pkg/config/buildconfig.go.in#L11C2-L11C2
* https://github.com/hpcng/warewulf/blob/546007423cff17d5bbdd966f7b392b6b0b20ab45/internal/pkg/config/tftp.go#L8

As the latter is not referenced by any code, we should remove it?

**Comment by anderbubble** [comment]
In theory I agree, but would that break (with a yaml parse error) existing installations that currently have a tftproot yaml variable set, even if it's not doing anything? Or will the parser ignore unknown values?

**Comment by anderbubble** [comment]
Decided to handle this in a different bit of effort, in discussion with @mslacken.
