### ISSUE TITLE
Remove compiled-in or configurable "defaults"

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#917]
Warewulf should not require the presence of any pre-defined defaults, either via `defaults.conf` or compiled in. Any "batteries included" functionality should be supplied by the presence of a pre-defined default profile in `nodes.conf`, but Warewulf should continue to work as sensibly as possible without even this defined, but without any compiled-in attribute values.

See for motivation:
* https://github.com/hpcng/warewulf/issues/895
* https://github.com/hpcng/warewulf/issues/661
* https://github.com/hpcng/warewulf/issues/520
* https://github.com/hpcng/warewulf/issues/451

**Comment by anderbubble** [comment]
@mslacken suggested that this is a bigger change than should go in 4.5, but @anderbubble is concerned that if we don't do it now we're introducing defaults.conf in 4.5, then taking it back away in 4.6.

@anderbubble is going to try to make a PR for discussion.

**Comment by mslacken** [comment]
#1020 will close this, but so this moves to 4.6.0
