### ISSUE TITLE
Improve the wwctl container list command

### ISSUE THREAD

**Issue by conxuro** [warewulf/warewulf#954]
### Summary

Improve the output of the `wwctl container list` command to show a more usefull size value by spliting it into several values. E.g. IMG (GZ) SIZE, for the uncompressed image size (compressed maybe into parenthesis) and TOTAL USE SIZE, for the total use in disk (as it is shown currently).

### Rationale

There is a discrepancy in the size shown by list command and the du and ls Linux commands and also "size" value can be confusing.

### Description

While using `wwctl container list` command the size of the image is shown as the addition of the chroot subdirectory size, and the .img and .img.gz files. It can be confusing since sizes are calculated with Go, and differs, in some cases significatively, from Linux commands (du and ls).

Also it is not really useful in terms of booting a node since not the whole space of a container in disk is loaded to a node but the img file size, which can be determinant, specially with Legacy boot.

Not really related, but columns tabs/spaces could be improved too, in order to have the values properly aligned to the headers.

### Additional information

Suggestion of output:
```
CONTAINER NAME   NODES  KERNEL VERSION   CREATION TIME        MODIFICATION TIME    IMG (GZ) SIZE   TOTAL USE SIZE
rocky-8-base   0      4.18.0-477.15.1.el8_8.x86_64 08 Aug 23 12:25 CEST 09 Aug 23 13:39 CEST 1.7 GiB (774 MiB) 4.2 GiB
```

Suggested changes:
- Two more size vars in `internal/pkg/api/container/container.go`
- New column(s) in `internal/app/wwctl/container/list/main.go`

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by anderbubble** [comment]
Let's just report the uncompressed image first. Optionally we can add flags to show the compressed image and/or the chroot.
