### ISSUE TITLE
Installation instructions fail on Rocky Linux 9.2

### ISSUE THREAD

**Issue by alansill** [warewulf/warewulf#977]
### Steps to reproduce

I am having trouble following the install instructions for warewulf at [https://warewulf.org/docs/development/quickstart/el9.html#install-warewulf-and-dependencies](https://warewulf.org/docs/development/quickstart/el9.html#install-warewulf-and-dependencies). 
Everything goes okay but when I use the install step (sudo make install) I get:
```make: *** No rule to make target ‘homealansillwarewulfvendorgithub.comcreastydefaultsdefaults.go’, needed by ‘wwctl’. Stop.``` 
Also looking over the output of the prior build steps there seems to be something odd abut the vendor setup. Issuing “go mod vendor” after a “make clean” gets this problem to go away but doesn’t resolve the “No rule to make target” problem above.
I’m doing this from a normal user account with sudoers privileges.

### Error message

```make: *** No rule to make target ‘homealansillwarewulfvendorgithub.comcreastydefaultsdefaults.go’, needed by ‘wwctl’. Stop```

### Information on your system

Rocky Linux 9.2 fresh installation on a Dell Optiplex.

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
Thanks for pointing this out, @alansill. There are other docs issues on the 4.5 milestone, including reworking the quick start guides; but I'll keep this open for now.

**Comment by OnurcanGms** [comment]
If you change row 122 "install -m 0755 $(DESTDIR)$(BINDIR)" with "install -m 0755 wwctl home/alansill/warewulf/vendor/github.com/creasty/defaults/defaults.go" in Makefile this step will pass. There may be a problem with $DESTDIR or $BINDIR varibles.

**Comment by alansill** [comment]
Please note that the firewall setup will probably need updating also. For my test instance, I had to configure the public, external, and internal rules in a way that makes sense to me but is different from the default currently being set up by the warewulf installation. I will play with this further and try to get to a repeatable set of steps, but meanwhile I advise testing on a fresh test cluster setup with new OS versions.
