### ISSUE TITLE
split default overlays into discrete functionality and test

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#987]
### Summary

Split the `generic` and `wwinit` overlays into multiple discrete overlays based on their functionality. For example, `wwinit` might be split into `NetworkManager`, `ifcfg`, `udev`, etc.

These overlays should then be explicitly included by the `default` profile (not implicitly included by a built-in setting).

### Rationale

The monolithic overlays make it difficult to opt-out of discrete parts of built-in Warewulf functionality.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by blixuga** [comment]
Assuming that #885 is going to be a prerequisite for this?

**Comment by anderbubble** [comment]
> Assuming that #885 is going to be a prerequisite for this?

Not specifically, though #885 will probably be merged in first anyway. (I just haven't gotten to it.)

**Comment by griznog** [comment]
I've been thinking about this quite a bit, encouraged my my ongoing experiment of multiple clusters/sites sharing a base set of overlays and today @anderbubble 's comment in #1208 sparked an idea. I'm now thinking:

* Warewulf distributed overlays go into `/usr/share/warewulf/overlays`.
* User defined overlays and modifications go into `/etc/warewulf/overlays`.
* A user overlay of the same name as a Warewulf Overlay overrides the warewulf overlay file-by-file during overlay building. 

Under this arrangement  if I only want to modify one file in the upstream overlay `ANOVERLAY`, I'd create `/etc/warewulf/overlays/ANOVERLAY` and put only my modifications in there, leaving the rpm-delivered overlay untouched. Locally defined overlays just need to not conflict with names of warewulf provided overlays, which could be addressed by prefix/suffix on warewulf provided overlay names. 

I think this would allow easy locally managed revision control for `/etc/warewulf/overlays` with just modifications to standard overlays and custom local overlays in this location. `rpm`/`dpkg` updates could optionally run a script to warn if an updated file is also present in the local overlay location. Bonus of this rolling overlays into any revision control already in use in `/etc/warewulf`.

griznog

**Comment by anderbubble** [comment]
I 100% agree with @griznog.
